- .gitignore
Exclude files created during install and normal operation
> Ignore some generated files

- htdocs/install/css/style.css
- htdocs/install/include/functions.php
- htdocs/install/include/makedata.php
- visual corruption on step list
- erroneous error regarding file_upload directive
- enable standard blocks (were not made visible due to *.tpl names)
> A few fixes to install

- htdocs/class/textsanitizer/youtube/youtube.php
- modernize youtube URL recognition, also accept just video ID
- responsive video sizing with bootstrap themes
- allow specifying width as 16x9 or 4x3 aspect
- calculate aspect if width and height specified
> Youtube handling enhancements suggested by xd9527

- htdocs/xoops_lib/modules/protector/class/protector.php
- upgrade/language.php
Also, revise protector dotdot check
> Remove eregi() uses

- htdocs/class/smarty/Smarty.class.php
- htdocs/class/smarty/Smarty_Compiler.class.php
Prevent possible "Methods with the same name as their class" issues.
> Smarty patch

- htdocs/Frameworks/art/object.php
- htdocs/class/module.textsanitizer.php
- htdocs/install/class/installwizard.php
- htdocs/install/include/functions.php
- htdocs/install/language/english/welcome.php
- htdocs/install/page_tablesfill.php
- htdocs/kernel/object.php
- htdocs/themes/xbootstrap/modules/newbb/newbb_viewtopic.tpl
Remediation of a few issues found since RC2.
Includes
- deprecating some things that will disappear by next release
- remove some MySQL V4 enabling code (not supported) and minor cleanups in installer
- fix a missed template extension change
> Some tweaks post RC2

- htdocs/Frameworks/moduleclasses/moduleadmin/moduleadmin.php
- htdocs/include/findusers.php
- htdocs/install/include/config.php
- htdocs/install/page_modcheck.php
- htdocs/modules/system/admin/modulesadmin/main.php
- htdocs/modules/system/admin/users/main.php
- Incorrect variable initialization
- 'uesr_findform' typo
- filter extension is required now
- nightmarish response to writable cache error
> Fix issues noticed in review

- htdocs/modules/pm/admin/about.php
- htdocs/modules/pm/admin/admin.php
- htdocs/modules/pm/admin/prune.php
- htdocs/modules/profile/admin/about.php
- htdocs/modules/profile/admin/category.php
- htdocs/modules/profile/admin/field.php
- htdocs/modules/profile/admin/index.php
- htdocs/modules/profile/admin/permissions.php
- htdocs/modules/profile/admin/step.php
- htdocs/modules/profile/admin/user.php
- htdocs/modules/system/class/block.php
- htdocs/modules/system/include/update.php
- htdocs/modules/system/themes/default/css/logger.css
- htdocs/modules/system/themes/legacy/css/style.css
- htdocs/xoops_lib/modules/protector/admin/about.php
- htdocs/xoops_lib/modules/protector/admin/index.php
addNavigation(basename(__FILE__)) plus few others changes
> addNavigation(basename(__FILE__))

- docs/lang_diff.txt
- htdocs/modules/system/themes/default/language/english/admin.php
- htdocs/modules/system/themes/default/xotpl/xo_accordion.tpl
> Change bug and code links in admin

- htdocs/modules/system/admin/images/main.php
> Assign by ref issue

- docs/lang_diff.txt
- htdocs/install/include/functions.php
- htdocs/install/language/english/install.php
- htdocs/install/page_configsave.php
> Update installer configuration file save

- htdocs/install/page_configsave.php
Scrutinizer-ci to the rescue again!
> Fix issue when posix functions not available

- docs/README.txt
- docs/fixing_permissions.txt
- docs/install.html
- docs/lang_diff.txt
- htdocs/admin.php
- htdocs/modules/system/themes/zetadigme/language/english/admin.php
- htdocs/modules/system/themes/zetadigme/xotpl/xo_accordion.tpl
- release_notes.txt
- Bring various scattered doc file up to date with 2.5.8
- Remove obsolete links to SourceForge, such as in issue #56
> Documentation review and link checks

- htdocs/modules/system/class/thumbs/phpthumb.bmp.php
- htdocs/modules/system/class/thumbs/phpthumb.filters.php
- htdocs/modules/system/class/thumbs/phpthumb.functions.php
- htdocs/modules/system/class/thumbs/phpthumb.ico.php
Some changes needed in phpthumb update in PR #66.
- PHP 7 compatibility
- security best practice
> Fix issues from phpthumb update

- htdocs/modules/system/themes/default/language/english/admin.php
> Point module source links to GitHub

- htdocs/class/logger/xoopslogger.php
- htdocs/class/xoopsload.php
- make XoopsLoad more resilient with include_once for module and framework classes
- add PHP version sensitive (5 vs 7) type check in exception handler
> Two small fixes

- docs/changelog.250.txt
- htdocs/include/version.php
> Release prep for RC3

- htdocs/modules/system/js/admin.js
- htdocs/modules/system/js/templates.js
- htdocs/xoops.css
This fixes #78.
Also small fix for recent jGrowl update.
> Templates Manager js issues

- htdocs/class/model/joint.php
- htdocs/kernel/object.php
> Fix XoopsModelJoint::getCountsByLink keyName_link bug

- htdocs/include/functions.php
> Banner Fixes

- htdocs/class/database/mysqldatabase.php
Follow recommendation from [PHP documentation](http://php.net/manual/en/mysqlinfo.concepts.charset.php).
Fixes #120
> Change set charset behavior for mysqli

- htdocs/class/smarty/xoops_plugins/function.securityToken.php
- htdocs/image.php
- htdocs/kernel/group.php
- htdocs/kernel/groupperm.php
- htdocs/kernel/online.php
- htdocs/language/english/locale.php
Cover several issues, some found during testing 2.5.8 modules in 2.6
- backport Smarty securityToken plugin (eliminates one need for php tag)
- add table property to some handlers not based on XoopsPersitableObjectHandler (table names changed, and the table property is a compatible way to obtain the the names from the handler.)
- more
> Misc fixes

- htdocs/modules/protector/language/english/help/help.tpl
Typo => limitaion = limitation
into
modules/protector/language/english/help/help.tpl
> Typo help.tpl

- htdocs/class/database/mysqldatabase.php
- htdocs/install/class/dbmanager.php
- htdocs/install/page_dbconnection.php
- htdocs/install/page_dbsettings.php
- htdocs/xoops_lib/modules/protector/class/protector.php
This condition is handled differently in mysqli than in the mysql extension, so in some cases errors would not be reported correctly, i.e. during install as in #139.
> Report error on database connection

- htdocs/modules/system/language/english/help/module_index.html
> Correct help/module_index in system

- htdocs/themes/xbootstrap/modules/system/system_siteclosed.tpl
replace harcoded placeholder for name and password
> update system_siteclosed for xbootstrap

- htdocs/browse.php
- htdocs/class/module.textsanitizer.php
- htdocs/class/textsanitizer/censor/censor.php
- htdocs/class/textsanitizer/flash/flash.php
- htdocs/class/textsanitizer/iframe/iframe.php
- htdocs/class/textsanitizer/image/image.php
- htdocs/class/textsanitizer/li/li.php
- htdocs/class/textsanitizer/mms/mms.php
- htdocs/class/textsanitizer/mp3/mp3.php
- htdocs/class/textsanitizer/readme.txt
- htdocs/class/textsanitizer/rtsp/rtsp.php
- htdocs/class/textsanitizer/soundcloud/soundcloud.php
- htdocs/class/textsanitizer/syntaxhighlight/syntaxhighlight.php
- htdocs/class/textsanitizer/textfilter/textfilter.php
- htdocs/class/textsanitizer/ul/ul.php
- htdocs/class/textsanitizer/wiki/wiki.php
- htdocs/class/textsanitizer/wmp/wmp.php
- htdocs/class/textsanitizer/youtube/youtube.php
Fix a couple of issues found in brief testing under latest PHP 7.1 beta
- reference issue in text sanitizer
- make clean exit after delivering file in browse.php
> PHP 7.1.0 fixes

- htdocs/class/tree.php
- reference issues (PHP 7+)
- some PSR2 cleanup
> XoopsObjectTree issues

- htdocs/class/xoopskernel.php
> xos_kernel_Xoops2 reference issues

- htdocs/class/pagenav.php
- htdocs/class/tree.php
- htdocs/class/xoopscomments.php
- htdocs/class/xoopsform/formcheckbox.php
- htdocs/class/xoopsform/formradio.php
- htdocs/class/xoopsform/formselect.php
- htdocs/class/xoopsform/grouppermform.php
- htdocs/class/xoopstree.php
> Move to HTML5 syntax

- htdocs/themes/xbootstrap/modules/publisher/publisher_display_list.tpl
- htdocs/themes/xbootstrap/modules/publisher/publisher_display_wfsection.tpl
- adding missing page navigation
- fixing "bold" in summary
> fixes for Publisher in xBootstrap

- htdocs/admin.php
- htdocs/class/captcha/recaptcha/recaptchalib.php
- htdocs/class/commentrenderer.php
- htdocs/class/tree.php
- htdocs/class/xoopsform/formelement.php
- htdocs/include/checklogin.php
- htdocs/include/comment_delete.php
- htdocs/include/comment_form.php
- htdocs/include/comment_post.php
- htdocs/include/comment_view.php
- htdocs/include/functions.php
- htdocs/install/class/dbmanager.php
- htdocs/kernel/member.php
- htdocs/kernel/module.php
- htdocs/kernel/session.php
- htdocs/modules/profile/activate.php
- htdocs/modules/profile/index.php
- htdocs/modules/profile/user.php
- htdocs/modules/system/admin.php
- htdocs/modules/system/admin/modulesadmin/modulesadmin.php
- htdocs/modules/system/blocks/system_blocks.php
- htdocs/modules/system/class/thumbs/phpthumb.class.php
- htdocs/modules/system/menu.php
- htdocs/modules/system/themes/default/menu.php
- htdocs/modules/system/themes/zetadigme/menu.php
- htdocs/register.php
- htdocs/search.php
- htdocs/user.php
- upgrade/upd-2.4.x-to-2.5.0/dbmanager.php
> Zyspec feature/compare type improvements

- htdocs/class/xoopsform/formtextdateselect.php
check for existance of language calendar.php file and if $GLOBALS['xoopsTpl] before it's used
> check for existance of file & object before use - XoopsFormTextDateSelect

- htdocs/class/libraries/composer.lock
- htdocs/class/libraries/vendor/composer/installed.json
- htdocs/class/libraries/vendor/xoops/xmf/src/Xmf/Request.php
Fixes #189 - Wrong class in stripSlashesRecursive
> Update to XMF 1.1.3

- htdocs/class/theme.php
Add realpath() to resolve any symbolic links before manipulating path.
> Small issue with symlinks

- htdocs/class/xoopsform/form.php
I added compatibility with PHP4
#202
> Compatibility in XoopsForm with php4

- htdocs/modules/system/themes/default/language/english/localsupport.php
- htdocs/modules/system/themes/zetadigme/language/english/localsupport.php
As reported in #146
Seems to be in comment block, but now relevant. Both default and zetadigme admin themes.
> Bad links in admin theme localsupport

- htdocs/install/include/config.php
- htdocs/install/include/install_tpl.php
- htdocs/install/language/english/install.php
- Language support link not opening due to stray colon
- Add curl to recommended extensions
- Move toward HTML5
> Install issues

- htdocs/modules/system/class/thumbs/phpThumb.php
- htdocs/modules/system/class/thumbs/phpthumb.bmp.php
- htdocs/modules/system/class/thumbs/phpthumb.class.php
- htdocs/modules/system/class/thumbs/phpthumb.functions.php
- htdocs/modules/system/class/thumbs/phpthumb.gif.php
- htdocs/modules/system/class/thumbs/phpthumb.ico.php
- htdocs/modules/system/class/thumbs/phpthumb.unsharp.php
> phpThumb to 1.7.14-201608101311

- htdocs/class/smarty/Config_File.class.php
- htdocs/class/smarty/Smarty.class.php
- htdocs/class/smarty/Smarty_Compiler.class.php
- htdocs/class/smarty/debug.tpl
- htdocs/class/smarty/internals/core.assemble_plugin_filepath.php
- htdocs/class/smarty/plugins/function.math.php
Upstream update, XOOPS patches (for PHP7) no longer needed
> Smarty v2.6.30

- htdocs/install/include/config.php
Add the ability to set 'closesite' and 'debug_mode' configuration options during the install.
> Install configuration options

- htdocs/class/xoopsform/formselecttheme.php
- htdocs/modules/profile/class/field.php
Added option to XoopsFormSelectTheme:
`* @param bool   $theme_set_allowed Flag to use only selectable theme`
Fixed issue #205
> Select theme

- htdocs/include/formdhtmltextarea.js
- htdocs/include/formdhtmltextarea_preview.php
> Fix bug XoopsFormDhtmlTextArea preview with UTF-8

- htdocs/class/theme.php
- htdocs/themes/xbootstrap/tpl/nav-menu.tpl
Allows theme to add a search box only when search is enabled.
Added to xBootstrap
> Add xoops_search assign

- upgrade/index.php
- upgrade/upd-2.4.x-to-2.5.0/dbmanager.php
Upgrade testing on PHP 5.3 failed.
Also, added "debug" flag to turn error_reporting on. To enable use *site-url*/upgrade/?debug=1
> PHP 5.3 regression in upgrade

- htdocs/class/captcha/image/scripts/image.php
- htdocs/class/captcha/recaptcha.php
- htdocs/class/captcha/recaptcha/recaptchalib.php
- htdocs/class/captcha/recaptcha2.php
- htdocs/class/captcha/xoopscaptcha.php
> Mambax7 feature/captcha

- htdocs/class/captcha/recaptcha2.php
> Rework curl code

- upgrade/index.php
> Login over IPV6 fails during upgrade

- upgrade/index.php
- upgrade/login.php
> Session IP address issues in upgrade

- upgrade/index.php
Remove extra code left after merge of #247
> Fix merge error in upgrade/index.php

- htdocs/modules/system/admin/modulesadmin/main.php
> Keep consistent use of $error variable

- htdocs/modules/system/admin/banners/main.php
> Fixed bug banner in admin

- htdocs/modules/system/templates/system_userinfo.html
- htdocs/modules/system/templates/system_userinfo.tpl
- htdocs/userinfo.php
> error in userinfo.php

- htdocs/class/textsanitizer/flash/flash.php
- htdocs/class/textsanitizer/youtube/youtube.php
- htdocs/class/theme.php
- htdocs/class/xoopsform/formbutton.php
- htdocs/class/xoopsform/formbuttontray.php
- htdocs/class/xoopsform/formcheckbox.php
- htdocs/class/xoopsform/formcolorpicker.php
- htdocs/class/xoopsform/formdhtmltextarea.php
- htdocs/class/xoopsform/formelementtray.php
- htdocs/class/xoopsform/formfile.php
- htdocs/class/xoopsform/formlabel.php
- htdocs/class/xoopsform/formpassword.php
- htdocs/class/xoopsform/formradio.php
- htdocs/class/xoopsform/formselect.php
- htdocs/class/xoopsform/formtext.php
- htdocs/class/xoopsform/formtextarea.php
- htdocs/class/xoopsform/formtextdateselect.php
Forms are compatible with bootstrap and old themes
> Bootstrap compatibility

- htdocs/class/xoopsform/renderer/XoopsFormRendererLegacy.php
Bug with checkbox in XoopsFormRendererLegacy.php
> Fix bug with checkbox in XoopsFormRendererLegacy.php

- htdocs/modules/system/templates/system_search.html
- htdocs/modules/system/templates/system_search.tpl
- htdocs/modules/system/xoops_version.php
- htdocs/search.php
Basic templates for search. Designers must add the new template to the theme
> Add template for search

- htdocs/class/xoopsform/renderer/XoopsFormRendererBootstrap3.php
> Hidden form issue

- htdocs/class/xoopsform/renderer/XoopsFormRendererBootstrap3.php
> Allow nested trays to work as expected

- htdocs/class/xoopsform/form.php
- htdocs/class/xoopsform/formelementtray.php
- htdocs/class/xoopsform/renderer/XoopsFormRendererBootstrap3.php
> Value display in checkbox and radio elements

- htdocs/modules/system/preloads/core.php
- htdocs/themes/xbootstrap/css/xoops.css
xoops.css conflicts with already loaded theme supplied css
Re: #294
> Do not include xoops.css on redirect

- htdocs/class/tree.php
> add a trigger error if you use makeSelBox().

- htdocs/modules/profile/include/install.php
- htdocs/modules/profile/include/update.php
- htdocs/modules/profile/xoops_version.php
- hide ICQ, AIM, YIM and MSNM fields by default (on new install)
- switch user_sig to use dhtml editor (on update or install)
- bump module version
Re: issue #317
> Profile updates

- .gitignore
- upgrade/cnt-2.2.x-to-2.3.0/index.php
- upgrade/cnt-2.2.x-to-2.3.0/language/english.php
- upgrade/language/english/upgrade.php
- upgrade/style.css
- upgrade/upd-2.0.13-to-2.0.14/index.php
- upgrade/upd-2.0.18-to-2.3.0/index.php
- upgrade/upd-2.0.18-to-2.3.0/language/english.php
- upgrade/upd-2.3.0-to-2.3.1/index.php
- upgrade/upd-2.3.3-to-2.4.0/index.php
- upgrade/upd-2.4.0-to-2.4.1/index.php
- upgrade/upd-2.4.x-to-2.5.0/index.php
- upgrade/upd-2.5.4-to-2.5.5/index.php
- upgrade/upd-2.5.5-to-2.5.6/index.php
- upgrade/upd-2.5.7-to-2.5.8/index.php
- upgrade/upd-2.5.8-to-2.5.9/index.php
Capture some cleanups from #224
> Upgrade Cleanups

- htdocs/class/xoopsform/formselectuser.php
XoopsFormSelectUser has visual issues when the presented with enough users to require the Remove unselected and Search users links.
> Select user buttons

- htdocs/install/page_dbconnection.php
- htdocs/modules/system/blocks/system_blocks.php
- htdocs/themes/xbootstrap/modules/newbb/newbb_index.tpl
- htdocs/themes/xbootstrap/modules/system/system_notification_select.tpl
- HTML5 style checked and selected
- template typo
> Miscellaneous minor fixes

- htdocs/modules/system/admin/comments/main.php
- htdocs/themes/xbootstrap/modules/pm/pm_readpmsg.tpl
- htdocs/themes/xbootstrap/modules/pm/pm_viewpmsg.tpl
Re: #322
- Controls on readpmsg clear message and user info
- align columns when message icon is present
> Revise xBootstrap pm templates

- htdocs/modules/system/admin/images/main.php
- htdocs/modules/system/language/english/admin/images.php
- htdocs/modules/system/templates/admin/system_images.html
- htdocs/modules/system/templates/admin/system_images.tpl
Adding fineupload in images admin
> Multi upload image (admin)

- htdocs/class/textsanitizer/flash/config.php
- htdocs/class/textsanitizer/syntaxhighlight/config.php
- htdocs/class/textsanitizer/syntaxhighlight/syntaxhighlight.php
- disable flash entry button by default
- remove dead geshi related code
> Text sanitizer cleanup

- htdocs/install/class/dbmanager.php
Fixes method return value in write context
> PHP 5.3 regression

- htdocs/modules/system/admin/comments/main.php
- htdocs/modules/system/templates/admin/system_comments.html
- htdocs/modules/system/templates/admin/system_comments.tpl
> Fix error by ref and add a link to display comments

- htdocs/class/xoopseditor/tinymce/tinymce/jscripts/tiny_mce/plugins/xoopsimagemanager/xoopsimagebrowser.php
- htdocs/class/xoopseditor/tinymce/tinymce/jscripts/tiny_mce/plugins/xoopsimagemanager/xoopsimagemanager.php
Fix error by ref
fix error with getimagesize and allow_url_fopen  = 0
> Fix tiny mce

- htdocs/themes/xbootstrap/modules/xoopstube/videoload.tpl
- htdocs/themes/xbootstrap/modules/xoopstube/xoopstube_index.tpl
- htdocs/themes/xbootstrap/modules/xoopstube/xoopstube_singlevideo.tpl
- htdocs/themes/xbootstrap/modules/xoopstube/xoopstube_videoload.tpl
- htdocs/themes/xbootstrap/modules/xoopstube/xoopstube_viewcat.tpl
replacing all define _MD_XTUBE_ with _MD_XOOPSTUBE_
> define corrections into xBootstrap for XoopsTube module

- htdocs/include/checklogin.php
- htdocs/include/common.php
- htdocs/kernel/session.php
Consistent handling of secure flag for session and remember me cookies.
> Secure flag on cookies

- htdocs/kernel/member.php
- htdocs/modules/profile/admin/deactivate.php
Prevent reuse of an activation key by a deactivated user.
> Reset actkey on activation

- htdocs/class/textsanitizer/wiki/wiki.php
Missed in earlier updates to text sanitizer extensions.
> Update textsanitizer Wiki imagery

- htdocs/modules/system/blocks/system_blocks.php
display username and avatar in userblock
> username and avatar in userblock

- htdocs/themes/xbootstrap/modules/lexikon/index.html
- htdocs/themes/xbootstrap/modules/lexikon/lexikon_rss.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_adminmenu.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_authorlist.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_bookmark.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_category.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_content.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_entry.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_header.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_index.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_letter.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_profile.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_request.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_rss.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_search.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_submit.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_syndication.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_tag_bar.tpl
- htdocs/themes/xbootstrap/modules/lexikon/lx_topten.tpl
See: http://xoops.org/modules/newbb/viewtopic.php?post_id=362192
> Add lexikon templates from bleek

- htdocs/install/include/install_tpl.php
- upgrade/upgrade_tpl.php
> Fix short tag error

- docs/changelog.250.txt
- docs/lang_diff.txt
- htdocs/include/version.php
> Change log and version

- htdocs/install/page_configsave.php
- htdocs/install/page_modcheck.php
- htdocs/install/page_tablesfill.php
> Issues 381 & 382

- htdocs/class/captcha/text.php
> Lock text and code on instantiation

- htdocs/modules/system/templates/admin/system_avatars.html
- htdocs/modules/system/templates/admin/system_avatars.tpl
- htdocs/modules/system/templates/admin/system_images.html
- htdocs/modules/system/templates/admin/system_images.tpl
> Fix bug with button

- htdocs/xoops_lib/modules/protector/class/protector.php
> Permit higher traffic for multi-file uploads

- htdocs/modules/profile/admin/user.php
> Add new user button

- htdocs/modules/profile/admin/user.php
> Add user button

- htdocs/search.php
> Fix error link in search.php

- htdocs/modules/profile/admin/user.php
- htdocs/modules/system/admin/users/main.php
> Consistent user_avatar on account creation

- htdocs/modules/profile/class/field.php
- htdocs/modules/profile/include/forms.php
> Handle non-array, set sane defaults

- htdocs/modules/profile/class/field.php
Handling errors on datatype change.
> Handling errors on datatype change.

- htdocs/modules/system/admin/modulesadmin/modulesadmin.php
> Undefined variable in some paths

- htdocs/install/language/english/welcome.php
No code change, just updating documentation
> Doc update

- htdocs/modules/profile/admin/user.php
- clear formselectuser cache on save
- return from update with same user selected
Re: #430
> More visibility for added user

- htdocs/include/comment_view.php
Correct issue with refresh of comments not working.
> Comment bar missing hidden elements

- htdocs/class/xoopsload.php
> Guard against external loading

- htdocs/modules/system/admin/groups/main.php
- htdocs/modules/system/admin/users/main.php
Substitute defines for hardcoded group ids
> Use XOOPS_GROUP_* defines

- htdocs/modules/system/admin/modulesadmin/main.php
- htdocs/modules/system/admin/modulesadmin/modulesadmin.php
- htdocs/modules/system/admin/preferences/main.php
Restore function inadvertently removed in f88f0a74e626174cb44661946884e0ff46d70aa1
> Clear caches on module updates

- docs/changelog.250.txt
- docs/lang_diff.txt
- htdocs/Frameworks/moduleclasses/moduleadmin/css/admin.css
- htdocs/Frameworks/moduleclasses/moduleadmin/language/english/main.php
- htdocs/Frameworks/moduleclasses/moduleadmin/moduleadmin.php
- htdocs/modules/pm/admin/about.php
- htdocs/modules/profile/admin/about.php
- htdocs/xoops_lib/modules/protector/admin/about.php
- changes from zyspec re: #442
- change donations in pm, profile and protector to use email address
> Updates for PayPal changes

- docs/lang_diff.txt
- htdocs/edituser.php
- htdocs/include/checklogin.php
- htdocs/include/common.php
- htdocs/language/english/user.php
- htdocs/modules/profile/index.php
- htdocs/modules/profile/templates/profile_userform.tpl
- htdocs/modules/profile/user.php
- htdocs/modules/system/blocks/system_blocks.php
- htdocs/modules/system/templates/system_userform.html
- htdocs/modules/system/templates/system_userform.tpl
- htdocs/user.php
- htdocs/xoops_lib/modules/protector/class/protector.php
- standardize setcookie() calls, including value and expiration in deletes
- remove obsolete "store user name in cookie" code
> Standardize use of usercookie

- upgrade/checkmainfile.php
Handle edge cases using non-standard group id conventions.
> Add group defines to rewrite data

- docs/README.txt
- docs/changelog.250.txt
- docs/lang_diff.txt
- htdocs/include/version.php
- release_notes.txt
Adding a short testing period due several recent changes. 
Hopefully this will be short, and we can move to RC.
Please help by testing!
> Release prep Beta3

- htdocs/themes/xbootstrap/README.md
- htdocs/themes/xbootstrap/theme.tpl
- htdocs/themes/xbootstrap/tpl/nav-menu.tpl
New features now enabled and options shown
> xBootstrap enable headhesive and submenu demo

- htdocs/themes/xbootstrap/modules/newbb/newbb_edit_post.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_index.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_index_menu.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_notification_select.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_online.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_search.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_searchresults.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_viewall.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_viewforum.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_viewforum_menu.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_viewpost.tpl
fixed bug
new bootstrap templates
> newbb bootstrap templates

- htdocs/include/functions.php
Improves appearance in Bootstrap3 environments, re: #468
> Add simple btn classes

- htdocs/class/model/write.php
> Serialize before escaping

- htdocs/kernel/object.php
> Return integer for XOBJ_DTYPE_INT

- htdocs/class/libraries/composer.dist.lock
- htdocs/class/libraries/vendor/composer/installed.json
- htdocs/class/libraries/vendor/xoops/xmf/src/Xmf/Highlighter.php
- htdocs/class/libraries/vendor/xoops/xmf/src/Xmf/Metagen.php
- Issues in Xmf\Highlighter, Xmf\Metagen
Re: XOOPS/xmf#33 and XOOPS/xmf#34
> Update to Xmf 1.2.9

- htdocs/modules/profile/admin/deactivate.php
- htdocs/modules/profile/templates/profile_userinfo.tpl
- htdocs/modules/system/admin/tplsets/jquery.php
- htdocs/modules/system/admin/tplsets/main.php
- htdocs/themes/xbootstrap/modules/profile/profile_userinfo.tpl
- htdocs/themes/xswatch/modules/profile/profile_userinfo.tpl
- add missing tokens
- file validation
> Fixes after review

- htdocs/modules/system/admin/users/main.php
> Fix botched assignment

- htdocs/include/site-closed.php
- htdocs/modules/system/themes/transition/transition.php
- site-closed template naming conventions issues causing white screen
- redirect in admin in some circumstances interferes with final system module update
> Upgrade Issues

- htdocs/class/textsanitizer/wiki/wiki.php
> Add omitted arguments to MytsWiki::decode()

- .gitattributes
- docs/changelog.250.txt
- htdocs/include/version.php
- release_notes.txt
Updating version, change log, etc.
> Release Prep RC2

- htdocs/modules/profile/index.php
> External URL filtering

- docs/changelog.250.txt
- htdocs/include/version.php
> Release Prep RC3

- docs/changelog.250.txt
- htdocs/include/version.php
> Release Prep XOOPS 2.5.9

- htdocs/install/page_dbsettings.php
From Nguyen Thanh Nguyen:
https://tsublogs.wordpress.com/2017/07/12/xoops-core-2-5-8-1-install-db-sql-injection/
https://tsublogs.wordpress.com/2017/04/24/xoops-core-2-5-8-1-install-db-cross-site-scripting/
> Escaping issues

- docs/changelog.250.txt
- htdocs/Frameworks/moduleclasses/moduleadmin/moduleadmin.php
> ModuleAdmin stylesheet inclusion

- htdocs/class/xoopsform/renderer/XoopsFormRendererBootstrap3.php
> Move MAX_FILE_SIZE element before file element

- htdocs/kernel/notification.php
- htdocs/modules/system/class/fineuploadhandler.php
- htdocs/modules/system/class/maintenance.php
Collection of small fixes
- fineupload PHP 7.1+ issue (upstream)
- assignment instead of comparison in system/class/maintenance.php
- reference errors in kernel/notification.php
> Misc. Fixes

- htdocs/image.php
- Fix call to non-existing exit400BadReq() function
- add some common legacy mimetypes which may be present in old databases
> Error in error handling

- upgrade/upd-2.5.9-to-2.5.10/index.php
- change meta_robots config to textbox instead of select (#579)
- copy existing protector configs to XOOPS_VAR_PATH/protector
> Upgrade for 2.5.10

- htdocs/install/include/config.php
- htdocs/install/include/makedata.php
- htdocs/install/language/english/welcome.php
- htdocs/install/page_siteinit.php
- meta_robots config as textbox (#579)
- email validation (#576)
- correct writable protector directory
- bump php recommendation to 7.1+
- tone down default keywords
> Installer updates for 2.5.10

- htdocs/class/module.textsanitizer.php
Warning: htmlspecialchars() expects parameter 2 to be int, unknown given in file /class/module.textsanitizer.php line 557
> ENT_QUOTES

- htdocs/class/commentrenderer.php
- htdocs/themes/xbootstrap/style.css
- htdocs/themes/xswatch/style.css
> Fix https://github.com/XOOPS/XoopsCore25/issues/600

- htdocs/themes/xswatch/modules/system/system_notification_list.tpl
Cleaning up an xswatch theme template
> Tweak notifications template

- htdocs/include/functions.php
- htdocs/install/include/functions.php
- htdocs/modules/system/blocks/system_blocks.php
- upgrade/upd-2.3.3-to-2.4.0/index.php
- upgrade/upd-2.4.0-to-2.4.1/index.php
> Remove unneeded mt_srand() calls

- htdocs/themes/xbootstrap/modules/system/system_notification_list.tpl
- htdocs/themes/xbootstrap/modules/system/system_notification_select.tpl
fix https://github.com/XOOPS/XoopsCore25/issues/634
> fix Xbootstrap and xswatch notification display

- htdocs/class/criteria.php
> Workaround for new Criteria(1,1)

- htdocs/modules/system/admin/modulesadmin/modulesadmin.php
> Missing space

- htdocs/xoops_lib/modules/protector/admin/prefix_manager.php
- htdocs/xoops_lib/modules/protector/language/english/admin.php
> the prefix setting is now in secure.php

- htdocs/modules/system/templates/admin/system_blocks_item.html
- htdocs/modules/system/templates/admin/system_blocks_item.tpl
> Remove unwanted space in links

- htdocs/banners.php
- htdocs/class/xoopsmailer.php
- htdocs/include/functions.legacy.php
- htdocs/lostpass.php
- htdocs/modules/pm/class/message.php
- htdocs/modules/profile/activate.php
- htdocs/modules/profile/changemail.php
- htdocs/modules/profile/lostpass.php
- htdocs/modules/profile/register.php
- htdocs/modules/system/admin/mailusers/main.php
Causes "Notice: Only variables should be assigned by reference"
> Unneeded by reference

- htdocs/modules/system/admin/avatars/main.php
> Implement Xmf\Request for input

- htdocs/install/sql/mysql.structure.sql
- upgrade/cnt-2.2.x-to-2.3.0/index.php
> Fix install error under MySQL in ANSI mode

- htdocs/modules/system/admin/users/jquery.php
- htdocs/modules/system/admin/users/users.php
As requested. 
> Note that I didn't do the unit test bit (I don't know PHP). 
What I have done for testing is renaming my XX_posts table to see that it effectively hit both closes of the if statement. I have finally confirmed that the synchronise buttons are now working as they should.
> Fixed #695 issue with synchronize in admin->users

- htdocs/class/xoopsform/renderer/XoopsFormRendererLegacy.php
Includes size, font and color selects.
Fixes #706
> Reset Typography Controls when focus lost

- htdocs/modules/system/templates/admin/system_images.html
- htdocs/modules/system/templates/admin/system_images.tpl
> Incorrect tooltip in image manager category list

- htdocs/class/theme.php
replacement: https://github.com/XOOPS/XoopsCore25/pull/716
> New module page

- htdocs/class/theme.php
https://github.com/XOOPS/XoopsCore25/issues/715
> Add smarty "xoops_modulepage"

- htdocs/modules/system/themes/default/xotpl/xo_modules.tpl
- htdocs/modules/system/themes/transition/xotpl/xo_modules.tpl
Remove HTML from title attribute used for tooltips.
Fixes #723
> Simplify tooltips

- htdocs/modules/system/class/thumbs/phpThumb.php
- htdocs/modules/system/class/thumbs/phpthumb.bmp.php
- htdocs/modules/system/class/thumbs/phpthumb.class.php
- htdocs/modules/system/class/thumbs/phpthumb.functions.php
- htdocs/modules/system/class/thumbs/phpthumb.gif.php
Patches to allow phpthumb to operate without deprecation notices in PHP 7.4
> phpthumb patches

- htdocs/class/mail/phpmailer/class.phpmailer.php
- htdocs/class/module.textsanitizer.php
- htdocs/class/uploader.php
- htdocs/image.php
- htdocs/xoops_lib/modules/protector/class/gtickets.php
- htdocs/xoops_lib/modules/protector/class/protector.php
Suppress deprecation errors that occur in PHP 7.4
> Silence magic quotes

- htdocs/class/theme.php
If specified theme does not have readable theme.tpl or theme.html, then:
- change to 'default' theme
- trigger error message
> Attempt graceful failure on missing theme

- htdocs/modules/system/admin/blocksadmin/main.php
> Get 'sel' vars from GET explicitly

- htdocs/class/theme.php
> Handle special case of admin themes in checks

- htdocs/modules/system/class/group.php
> Get description for edit

- htdocs/class/xoopsform/renderer/XoopsFormRendererBootstrap4.php
The calendar is now glued to the input!
I wanted to add this:
[https://getbootstrap.com/docs/4.4/components/forms/#file-browser](https://getbootstrap.com/docs/4.4/components/forms/#file-browser)
for renderFormFile.
But I can't do it right! Do you think it's interesting?
> fix calandar

- htdocs/include/functions.php
- htdocs/modules/system/templates/system_confirm.tpl
- htdocs/modules/system/xoops_version.php
- htdocs/themes/xbootstrap/modules/system/system_confirm.tpl
> use smarty in xoops_confirm()

- htdocs/modules/profile/class/field.php
> Remove dead list type

- htdocs/modules/system/language/english/help/blocksadmin.html
Add "Tips" section including some less than obvious features.
> Update Help page for blocks admin

- htdocs/themes/xbootstrap/modules/newbb/newbb_edit_post.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_index.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_index_menu.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_notification_select.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_online.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_search.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_searchresults.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_thread.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_viewall.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_viewforum.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_viewforum_menu.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_viewforum_subforum.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_viewpost.tpl
- htdocs/themes/xbootstrap/modules/newbb/newbb_viewtopic.tpl
- htdocs/themes/xbootstrap/modules/obituaries/obituaries_user.tpl
- htdocs/themes/xbootstrap/modules/obituaries/obituaries_users.tpl
- htdocs/themes/xbootstrap/modules/tdmdownloads/tdmdownloads_index.tpl
- htdocs/themes/xbootstrap/modules/tdmdownloads/tdmdownloads_viewcat.tpl
- htdocs/themes/xswatch/modules/obituaries/obituaries_user.tpl
- htdocs/themes/xswatch/modules/obituaries/obituaries_users.tpl
- htdocs/themes/xswatch/modules/tdmdownloads/tdmdownloads_index.tpl
- htdocs/themes/xswatch/modules/tdmdownloads/tdmdownloads_viewcat.tpl
Tweaks to xbootstrap templates
- use newbb module supplied templates
- reference obituaries assets folder for images
- reference tdmdownloads assets folder for images
Tweaks to xswatch templates
- reference obituaries assets folder for images
- reference tdmdownloads assets folder for images
> Updates to bootstrap v3 based themes

- htdocs/themes/xbootstrap/modules/newbb/newbb_index.tpl
- htdocs/themes/xswatch/modules/newbb/newbb_index.tpl
> Fix NEWBB_NOTOPIC error

- htdocs/kernel/notification.php
> Fix docblock \XoopsNotificationHandler::triggerEvent()

- htdocs/modules/pm/admin/index.html
- htdocs/modules/pm/admin/index.php
- htdocs/themes/xswatch4/modules/pm/pm_viewpmsg.tpl
- add a meaningful default page in admin section
- tweek xswatch4 template for theme's standard pagenav style
> Small tweek to pm module

- htdocs/themes/xswatch4/README.md
- htdocs/themes/xswatch4/modules/xmnews/blocks/xmnews_block.tpl
- htdocs/themes/xswatch4/modules/xmnews/blocks/xmnews_block_colonnes.tpl
- htdocs/themes/xswatch4/modules/xmnews/blocks/xmnews_block_lignes.tpl
- htdocs/themes/xswatch4/modules/xmnews/xmnews_article.tpl
- htdocs/themes/xswatch4/modules/xmnews/xmnews_index.tpl
- Missed : when no modified date exists
- Customize blocks (in lines / in columns)
- Optimisation for the truncated titles, in blocks
> cosmetic bt4 modifications

- htdocs/modules/profile/index.php
https://github.com/XOOPS/XoopsCore25/issues/559
> Fix Profile Index Template

- htdocs/modules/system/admin/users/main.php
> Admin user sync

- htdocs/language/english/global.php
https://github.com/XOOPS/XoopsCore25/issues/837
> change of _MEDIUMDATESTRIN

- htdocs/themes/xbootstrap/modules/newbb/newbb_viewall.tpl
- htdocs/themes/xswatch/modules/newbb/newbb_viewall.tpl
Removes spurious characters in page navigation URLs
> Template patches for Newbb 5.0 Final

- htdocs/kernel/object.php
> Return proper null value for integer columns

- htdocs/include/common.php
Not the ideal solution and subject to change, but sufficient to allow some testing.
> Patch a few issues when using PHP 8

- htdocs/class/xoopsform/formselectuser.php
> Add all selected users in XoopsFormSelectUser

- htdocs/modules/pm/templates/pm_pmlite.tpl
- htdocs/modules/pm/templates/pm_readpmsg.tpl
- htdocs/modules/pm/templates/pm_viewpmsg.tpl
- htdocs/modules/system/templates/blocks/system_block_mainmenu.tpl
- htdocs/themes/xbootstrap/modules/pm/pm_viewpmsg.tpl
- htdocs/themes/xbootstrap/modules/system/blocks/system_block_mainmenu.tpl
- htdocs/themes/xswatch/modules/pm/pm_viewpmsg.tpl
- htdocs/themes/xswatch/modules/system/blocks/system_block_mainmenu.tpl
- htdocs/themes/xswatch4/modules/pm/pm_viewpmsg.tpl
Adds default values for variable which may not be set
> Fix errors seen in PHP 8 in pm module templates

- htdocs/class/xoopsform/renderer/XoopsFormRenderer.php
> Magic __wakeup() method must be public

- htdocs/Frameworks/moduleclasses/moduleadmin/moduleadmin.php
> Remove debug info

- htdocs/lostpass.php
- htdocs/modules/profile/lostpass.php
- htdocs/modules/profile/templates/profile_breadcrumbs.tpl
- htdocs/modules/profile/templates/profile_editprofile.tpl
- htdocs/modules/profile/templates/profile_form.tpl
- htdocs/modules/profile/templates/profile_results.tpl
- htdocs/modules/profile/templates/profile_userform.tpl
- htdocs/modules/profile/templates/profile_userinfo.tpl
- htdocs/modules/system/templates/blocks/system_block_login.tpl
- htdocs/modules/system/templates/blocks/system_block_mainmenu.tpl
- htdocs/modules/system/templates/system_userform.html
- htdocs/modules/system/templates/system_userform.tpl
- htdocs/themes/xbootstrap/modules/profile/profile_userform.tpl
- htdocs/themes/xbootstrap/modules/profile/profile_userinfo.tpl
- htdocs/themes/xbootstrap/modules/system/blocks/system_block_login.tpl
- htdocs/themes/xbootstrap/modules/system/system_userform.tpl
- htdocs/themes/xswatch/modules/profile/profile_userform.tpl
- htdocs/themes/xswatch/modules/profile/profile_userinfo.tpl
- htdocs/themes/xswatch/modules/system/blocks/system_block_login.tpl
- htdocs/themes/xswatch/modules/system/system_userform.tpl
- htdocs/themes/xswatch4/modules/profile/profile_breadcrumbs.tpl
- htdocs/themes/xswatch4/modules/profile/profile_form.tpl
- htdocs/themes/xswatch4/modules/profile/profile_userform.tpl
- htdocs/themes/xswatch4/modules/profile/profile_userinfo.tpl
- htdocs/themes/xswatch4/modules/system/blocks/system_block_login.tpl
- htdocs/themes/xswatch4/modules/system/system_userform.tpl
Fixes for system user and profile module issues found during PHP 8 testing
> Template fixes user and profile for php8

- htdocs/class/logger/xoopslogger.php
> Remove debugging code

- htdocs/modules/system/admin/modulesadmin/modulesadmin.php
https://stackoverflow.com/questions/5879675/problem-with-fatal-error-operator-not-supported-for-strings-in
> short array push syntax on a string

- htdocs/modules/system/templates/admin/system_avatars.html
- htdocs/modules/system/templates/admin/system_avatars.tpl
- htdocs/modules/system/templates/admin/system_images.html
- htdocs/modules/system/templates/admin/system_images.tpl
- htdocs/modules/system/templates/system_imagemanager2.html
- htdocs/modules/system/templates/system_imagemanager2.tpl
- htdocs/themes/xswatch4/modules/wggallery/wggallery_upload.tpl
Should have only one underscore. Seeing different results in different php versions.
> Malformed constant __MINWIDTHIMAGEERROR

- htdocs/class/captcha/text.php
- htdocs/themes/default/style.css
- htdocs/themes/xbootstrap/css/xoops.css
- htdocs/themes/xswatch/css/xoops.css
- htdocs/themes/xswatch4/css/xoops.css
I created a css class for the text captcha. Today we cannot personalize the display according to the theme. This modification is very important to be able to use several themes.
> Class css for captcha text

- htdocs/themes/xswatch4/modules/xmcontact/blocks/xmcontact_contact.tpl
- htdocs/themes/xswatch4/modules/xmcontact/blocks/xmcontact_contactform.tpl
- htdocs/themes/xswatch4/modules/xmcontact/xmcontact_form.tpl
- htdocs/themes/xswatch4/modules/xmcontact/xmcontact_index.tpl
- htdocs/themes/xswatch4/modules/xmcontent/blocks/xmcontent_block.tpl
- htdocs/themes/xswatch4/modules/xmcontent/xmcontent_action.tpl
- htdocs/themes/xswatch4/modules/xmcontent/xmcontent_index.tpl
- htdocs/themes/xswatch4/modules/xmcontent/xmcontent_viewcontent.tpl
- htdocs/themes/xswatch4/modules/xmdoc/blocks/xmdoc_block.tpl
- htdocs/themes/xswatch4/modules/xmdoc/xmdoc_action.tpl
- htdocs/themes/xswatch4/modules/xmdoc/xmdoc_docmanager.tpl
- htdocs/themes/xswatch4/modules/xmdoc/xmdoc_index.tpl
- htdocs/themes/xswatch4/modules/xmdoc/xmdoc_viewdoc.tpl
- htdocs/themes/xswatch4/modules/xmnews/blocks/xmnews_block.tpl
- htdocs/themes/xswatch4/modules/xmnews/blocks/xmnews_block_colonnes.tpl
- htdocs/themes/xswatch4/modules/xmnews/blocks/xmnews_block_lignes.tpl
- htdocs/themes/xswatch4/modules/xmnews/xmnews_action.tpl
- htdocs/themes/xswatch4/modules/xmnews/xmnews_article.tpl
- htdocs/themes/xswatch4/modules/xmnews/xmnews_index.tpl
> Update xmtemplates php8

- docs/lang_diff.txt
- htdocs/include/registerform.php
- htdocs/language/english/user.php
- htdocs/modules/profile/include/forms.php
- htdocs/themes/xbootstrap/modules/profile/profile_register.tpl
- htdocs/themes/xswatch/modules/profile/profile_register.tpl
- htdocs/themes/xswatch4/modules/profile/profile_register.tpl
I modified the templates to use bootstrap alerts.
I also added a description in the form to indicate the minimum and maximum lengths of the Username.
I did the same for the minimum length of the Password.
The modifications work with and without the profile module.
This should fix this problem:
https://github.com/XOOPS/XoopsCore25/issues/902
> Message profil

- docs/lang_diff.txt
Update docs/lang_diff.txt for #906
Comment: https://github.com/XOOPS/XoopsCore25/commit/86090f2f68e3821a3677ee0b4ae8402794fdd621#commitcomment-44102999
> Diff for 906 update

- docs/lang_diff.txt
- htdocs/class/xoopsmailer.php
- htdocs/modules/system/admin/mailusers/main.php
- htdocs/modules/system/language/english/admin/mailusers.php
https://github.com/XOOPS/XoopsCore25/issues/919
> add {X_NAME} tag for mailusers

- htdocs/class/textsanitizer/youtube/youtube.php
- htdocs/class/xoopsform/renderer/XoopsFormRendererBootstrap3.php
- htdocs/class/xoopsform/renderer/XoopsFormRendererBootstrap4.php
- htdocs/class/xoopsform/renderer/XoopsFormRendererLegacy.php
- scripts missing or duplicated in some circumstances
- error when youtube prompt canceled
> Fix issues in DHTMLTextArea support

- htdocs/include/site-closed.php
> Add {X_SITEURL} and {X_YEAR} to site closed page

- htdocs/modules/system/admin/modulesadmin/modulesadmin.php
add a link to the activated module
> fix for  "array to string conversion error"

- htdocs/modules/profile/index.php
- htdocs/modules/profile/user.php
- htdocs/user.php
The file htdocs/user.php is the gateway to user functions such as login, forgot password. If the profile module is installed, then htdocs/modules/profile/user.php takes over. In certain circumstances htdocs/modules/profile/index.php is called upon with the expectation it will mimic user.php.
These three programs have nearly identical definitions, and yet have diverged, the most significant concern is with handing of security considerations.
This commit standardizes the approach to input validation across all the variants, and eliminates the code separation within the profile module user.php and index.php scripts.
> Standardize user.php functions

- htdocs/modules/profile/admin/step.php
- htdocs/themes/xswatch4/modules/profile/profile_register.tpl
> Add sort on step_order, fix form

- htdocs/modules/system/class/gui.php
display Go to module only if the module has a user part
display block only if there are blocks
display comments only if there are  comments
> Now the admin menu only displays useful links:

- htdocs/modules/system/templates/system_redirect.html
- htdocs/modules/system/templates/system_redirect.tpl
- htdocs/themes/default/modules/system/system_redirect.tpl
> Add default for $xoops_logdump

- htdocs/modules/system/admin/modulesadmin/main.php
some modules have it like $modversion['version'] = '2.5.1';
> fix for version number as string

- htdocs/user.php
> Incorrect template specified

- htdocs/kernel/member.php
- htdocs/modules/system/admin/users/main.php
- htdocs/modules/system/templates/admin/system_users.html
- htdocs/modules/system/templates/admin/system_users.tpl
Several tweaks to hopefully reduce the resource burdens associated with the admin users page with large user bases.
> Improve performance of admin users page

- htdocs/class/cache/file.php
- htdocs/class/smarty/xoops_plugins/compiler.xoAdminIcons.php
- htdocs/class/smarty/xoops_plugins/compiler.xoModuleIcons32.php
- htdocs/class/smarty/xoops_plugins/compiler.xoModuleIconsBookmarks.php
- htdocs/include/cp_functions.php
- upgrade/upd_2.5.10-to-2.5.11/index.php
- Remove index.html files replaced by index.php files during upgrade if permissions allow
- Fix instances where an index.html file is created
- Fix instances where the presence of an index.html file is checked
> Removing dependencies on index.html files

- htdocs/modules/system/blocks/system_blocks.php
fix https://github.com/XOOPS/XoopsCore25/issues/637
> Block 'Waiting Contents' is deprecated

- htdocs/misc.php
- htdocs/modules/system/templates/system_misc_avatars.tpl
- htdocs/modules/system/templates/system_misc_friend.tpl
- htdocs/modules/system/templates/system_misc_online.tpl
- htdocs/modules/system/templates/system_misc_smilies.tpl
- htdocs/modules/system/xoops_version.php
Add the following templates:
- system_misc_avatars.tpl
- system_misc_friend.tpl
- system_misc_online.tpl
- system_misc_smilies.tpl
This makes the 4 primary uses of misc.php's showpopups themeable.
This PR only adds the default templates. Theme specific overrides still need to be done.
Re: #996
> Add templates to misc.php

- htdocs/themes/xswatch4/README.md
- htdocs/themes/xswatch4/modules/system/system_popup_header.tpl
- htdocs/themes/xswatch4/theme.tpl
- htdocs/themes/xswatch4/tpl/xswatchCss.tpl
- htdocs/themes/xswatch4/tpl/xswatchDarkCss.tpl
Allow for specifying light and dark themes that will switch based on user's preference
Re: #997
> Introduce prefers-color-scheme media queries

- htdocs/modules/system/include/functions.php
Remove dead inside of deprecated for PHP 8 compatibility
> Remove FILTER_SANITIZE_MAGIC_QUOTES in system_CleanVars()

- htdocs/install/include/createconfigform.php
- htdocs/themes/default/theme.ini
- htdocs/themes/xbootstrap/theme.ini
- htdocs/themes/xswatch/theme.ini
- htdocs/themes/xswatch4/theme.ini
A little explanation during the process seems appropriate. Of course, after seeing them on the page, a few adjustments in the ini files were in order.
> Show theme description in Select Theme install dialog

- htdocs/kernel/online.php
Reverts XOOPS/XoopsCore25#1005
This introduced a new problem. Reverting while investigating.
> Revert "Fix bug with bloc on-line."

- htdocs/install/include/config.php
- release_notes.txt
> Add uploads/files directory to writable list

- htdocs/misc.php
Has been displaying all, defeating the purpose of the display column.
> Respect smilies table display column

- htdocs/themes/xswatch4/css-slate/xoops.css
Based on user feedback on recent changes: 
> The xswatch4 Dark theme is fine but the text fields are white.
https://github.com/XOOPS/XoopsCore25/issues/997#issuecomment-808949297
> Darken form entry fields

- htdocs/themes/xbootstrap/language/english/main.php
it will be defined in NewBB for Default theme
> THEME_FORUM_REPLY

- htdocs/themes/xswatch4/modules/system/system_misc_avatars.tpl
- htdocs/themes/xswatch4/modules/system/system_misc_friend.tpl
- htdocs/themes/xswatch4/modules/system/system_misc_online.tpl
- htdocs/themes/xswatch4/modules/system/system_misc_smilies.tpl
- avatars
- friends (Recommanded us)
- smilies
- online (Just add a close button on top from my previous version)
> Bootstrap4 templates from misc.php

- htdocs/class/xoopsload.php
> Add xoopsformrendererbootstrap5 to XoopsLoad

- htdocs/modules/system/admin/maintenance/main.php
> Fix incorrect path names

- htdocs/themes/xswatch4/theme.tpl
- Changed http to https
- Moved logo in the < footer  > and deleted the next  < div >
> Cosmetic changes in theme.tpl - xswatch4 theme

- htdocs/themes/xswatch4/README.md
- htdocs/themes/xswatch4/css/my_xoops.css
- htdocs/themes/xswatch4/css/my_xoops_dark.css
- htdocs/themes/xswatch4/theme.tpl
- htdocs/themes/xswatch4/tpl/centerFooter.tpl
- htdocs/themes/xswatch4/tpl/content-zone.tpl
- htdocs/themes/xswatch4/tpl/leftBottom.tpl
- htdocs/themes/xswatch4/tpl/leftFooter.tpl
- htdocs/themes/xswatch4/tpl/rightBottom.tpl
- htdocs/themes/xswatch4/tpl/rightFooter.tpl
2 things:
- Better syntax for Bootstrap grid
- Add my_xoops.css file to customize css definitions and override Bootstrap definitions
> xSwatch4 options

- htdocs/admin.php
fix: https://github.com/XOOPS/XoopsCore25/issues/1103
> add admin.css

- htdocs/modules/system/templates/admin/system_header.html
- htdocs/modules/system/templates/admin/system_header.tpl
- htdocs/modules/system/themes/dark/modules/system/admin/system_header.tpl
> Add default for xo_sys_breadcrumb

- htdocs/modules/system/class/block.php
Fix: https://github.com/XOOPS/XoopsCore25/issues/1122
> add dirname in block title

- docs/lang_diff.txt
- htdocs/modules/system/admin/modulesadmin/modulesadmin.php
- htdocs/modules/system/language/english/admin/modulesadmin.php
Fix: https://github.com/XOOPS/XoopsCore25/issues/810
> Change define in the system module

- htdocs/modules/profile/preloads/core.php
fix: https://github.com/XOOPS/XoopsCore25/issues/1129
> add missing argument

- htdocs/xoops_lib/modules/protector/class/gtickets.php
Fix: https://github.com/XOOPS/XoopsCore25/issues/1137
> Change mcrypt_create_iv() to random_bytes()

- htdocs/themes/xswatch4/modules/xmcontact/blocks/xmcontact_contactform.tpl
- htdocs/themes/xswatch4/modules/xmcontact/xmcontact_form.tpl
- htdocs/themes/xswatch4/modules/xmcontact/xmcontact_index.tpl
- htdocs/themes/xswatch4/modules/xmcontent/blocks/xmcontent_block.tpl
- htdocs/themes/xswatch4/modules/xmcontent/xmcontent_action.tpl
- htdocs/themes/xswatch4/modules/xmcontent/xmcontent_index.tpl
- htdocs/themes/xswatch4/modules/xmcontent/xmcontent_viewcontent.tpl
- htdocs/themes/xswatch4/modules/xmdoc/xmdoc_viewdoc.tpl
- htdocs/themes/xswatch4/modules/xmnews/blocks/xmnews_block_waiting.tpl
- htdocs/themes/xswatch4/modules/xmnews/xmnews_action.tpl
- htdocs/themes/xswatch4/modules/xmnews/xmnews_article.tpl
- htdocs/themes/xswatch4/modules/xmnews/xmnews_index.tpl
- htdocs/themes/xswatch4/modules/xmsocial/xmsocial_social.tpl
> Updated XM module templates

- htdocs/modules/system/class/maintenance.php
Fix: https://github.com/XOOPS/XoopsCore25/issues/1041
> The index.php file is deleted and created after a cache delete operation

- htdocs/modules/system/admin/modulesadmin/modulesadmin.php
Fix: https://github.com/XOOPS/XoopsCore25/issues/814
> Link for 'This Module Admin' after module install

- htdocs/include/findusers.php
@zyspec: Jim, there are still few left, because I wasn't sure how to best convert them, since they could be array or string.
Of course, I could also make mistakes with what I did, so please take a close and critical look into it. This is not tested...
> request_findusers

- htdocs/modules/system/templates/system_search.tpl
- htdocs/themes/xswatch4/modules/system/system_search.tpl
https://github.com/XOOPS/XoopsCore25/issues/1158
> Undefined constant "next"

- htdocs/themes/xswatch4/css-cosmo/xoops.css
- htdocs/themes/xswatch4/css-cyborg/xoops.css
Ok I checked all files xoops.css (22)
> xoops.css url "/image/"

- htdocs/class/xoopsform/formelement.php
From montuy337513, fixes #1114
> Fix bug issue #1114

- htdocs/include/functions.php
- htdocs/modules/system/admin/groups/main.php
- htdocs/modules/system/admin/users/main.php
> Correct docblock for getHandler and getModuleHandler

- htdocs/class/xoopsform/formcaptcha.php
I propose 2 possibilities to correct this https://github.com/XOOPS/XoopsCore25/issues/1119
> Formcaptcha option2

- htdocs/kernel/object.php
> Fix Passing null to parameter ... of type string errors

- htdocs/kernel/configoption.php
> Add missing \XoopsConfigOptionHandler::getCount() method

- htdocs/kernel/configitem.php
> Passing null to parameter of type string

- htdocs/class/model/read.php
> Respect method arguments $start and $limit

- htdocs/Frameworks/moduleclasses/moduleadmin/moduleadmin.php
- htdocs/kernel/module.php
I suspect that  #1091 and  #1113  are related.
> \XoopsModule::$adminmenu not always properly initialized

- htdocs/class/smarty/xoops_plugins/compiler.xoAppUrl.php
> Null to string issue in xoAppUrl

- htdocs/class/template.php
- htdocs/kernel/module.php
- upgrade/upd_2.5.10-to-2.5.11/index.php
https://github.com/XOOPS/XoopsCore25/pull/1126
> scrutinizer3 

- htdocs/install/sql/mysql.structure.sql
- upgrade/upd_2.5.10-to-2.5.11/index.php
Fix: https://github.com/XOOPS/XoopsCore25/issues/1202
> varchar(12) to varchar(32) version

- htdocs/modules/system/admin/modulesadmin/modulesadmin.php
in file /modules/system/admin/modulesadmin/modulesadmin.php line 230
> trim() expects parameter 1 to be string, array given

- htdocs/modules/system/help.php
https://github.com/XOOPS/XoopsCore25/issues/482
> Add .tpl extension option for module_index help file #482

- htdocs/class/criteria.php
- htdocs/kernel/object.php
- htdocs/modules/pm/readpmsg.php
- htdocs/modules/pm/viewpmsg.php
- htdocs/readpmsg.php
- htdocs/viewpmsg.php
> Some php8.1 fixes

- htdocs/xoops_lib/modules/protector/class/protector.php
- htdocs/xoops_lib/modules/protector/filters_disabled/postcommon_post_register_moratorium.php
- htdocs/xoops_lib/modules/protector/include/postcheck_functions.php
- htdocs/xoops_lib/modules/protector/include/precheck_functions.php
Focus on:
- unserialize() settings
- a potential issue in a regex
> Reviewing Protector

- htdocs/install/page_dbsettings.php
It creates Fatal mysqli_sql_exception Unknown database '2511test8' file: \install\page_dbsettings.php : 62
> In PHP 8.1, the default error handling is set to throw an exception

- htdocs/install/include/makedata.php
> Implement new module version in system module install

- htdocs/class/libraries/vendor/boenrobot/money_format_polyfill/.gitignore
- htdocs/class/libraries/vendor/boenrobot/money_format_polyfill/LICENSE
- htdocs/class/libraries/vendor/boenrobot/money_format_polyfill/composer.json
- htdocs/class/libraries/vendor/boenrobot/money_format_polyfill/phpcs.xml
- htdocs/class/libraries/vendor/boenrobot/money_format_polyfill/src/money_format.php
- htdocs/class/libraries/vendor/firebase/php-jwt/src/Key.php
- htdocs/class/libraries/vendor/xoops/xmf/.github/workflows/pr_tests.yml
> Missing files from PR 1227

- htdocs/class/module.textsanitizer.php
Was processing inside existing HTML anchors
> Correct \MyTextSanitizer::makeClickable()

- docs/changelog.250.txt
- htdocs/install/class/pathcontroller.php
- htdocs/install/include/config.php
See Issue https://github.com/XOOPS/XoopsCore25/issues/1248
> change folder sorting in Installation, Issue #1248 (alain01/mamba)

- htdocs/modules/system/templates/system_search.tpl
- htdocs/search.php
- htdocs/themes/xswatch4/modules/system/system_search.tpl
> Issues 1269

- htdocs/kernel/user.php
practical option that is important
> adding the link on the name as in (XoopsUserUtility::getUnameFromId).

- upgrade/upd_2.5.10-to-2.5.11/index.php
> Fix issues in moving captcha configuration files

- htdocs/kernel/user.php
rather than hardcoding the values.
> Used notification_constants in XoopsUser

- htdocs/class/pagenav.php
fix: https://github.com/XOOPS/XoopsCore25/issues/1293
> fix php8.2 error

- htdocs/kernel/module.php
- htdocs/xoops_lib/modules/protector/oninstall.php
- htdocs/xoops_lib/modules/protector/onuninstall.php
Could provoke a PHP 7 Fatal error ([] operator not supported for strings).
> [] operator not supported for strings

- docs/README.txt
- docs/changelog.250.txt
- docs/install.html
- htdocs/include/version.php
Updates for version 2.5.11-RC1
> 2.5.11 RC1 prep

- htdocs/modules/system/templates/admin/system_avatars.html
- htdocs/modules/system/templates/admin/system_blocks.html
- htdocs/modules/system/templates/admin/system_blocks.tpl
- htdocs/modules/system/templates/admin/system_images.html
- htdocs/modules/system/templates/admin/system_images.tpl
- htdocs/modules/system/templates/admin/system_index.html
- htdocs/modules/system/templates/admin/system_index.tpl
- htdocs/modules/system/templates/admin/system_modules.html
- htdocs/modules/system/templates/admin/system_modules.tpl
- htdocs/modules/system/templates/admin/system_smilies.html
- htdocs/modules/system/templates/admin/system_smilies.tpl
- htdocs/modules/system/templates/admin/system_userrank.html
- htdocs/modules/system/templates/admin/system_userrank.tpl
- htdocs/modules/system/themes/dark/modules/system/admin/system_modules.tpl
See: https://github.com/XOOPS/XoopsCore25/issues/1333
> System_modules.tpl wrong quotations

- docs/lang_diff.txt
https://github.com/XOOPS/XoopsCore25/issues/1321
> updating lang_diff.txt

- htdocs/backend.php
- htdocs/class/template.php
- htdocs/class/theme.php
- htdocs/class/theme_blocks.php
- htdocs/header.php
- htdocs/include/site-closed.php
- htdocs/modules/system/admin.php
- htdocs/modules/system/admin/banners/main.php
- htdocs/modules/system/admin/blocksadmin/main.php
- htdocs/modules/system/admin/comments/main.php
- htdocs/modules/system/admin/groups/main.php
- htdocs/modules/system/admin/images/main.php
- htdocs/modules/system/admin/preferences/main.php
- htdocs/modules/system/admin/smilies/main.php
- htdocs/modules/system/admin/userrank/main.php
- htdocs/modules/system/admin/users/main.php
- htdocs/modules/system/class/gui.php
- htdocs/modules/system/help.php
- htdocs/search.php
I checked all the functions of the SmartyBC class and I made the modifications to use the smarty 4 compatible classes
> Compatibility smarty 3 and4

- htdocs/modules/system/templates/admin/system_modules.tpl
- htdocs/modules/system/templates/blocks/system_block_mainmenu.tpl
- htdocs/modules/system/themes/transition/xotpl/xo_globalnav.tpl
- htdocs/modules/system/themes/transition/xotpl/xo_metas.tpl
- htdocs/modules/system/themes/transition/xotpl/xo_page.tpl
This addresses "Undefined array key" errors in templates
> using empty check instead of default

- htdocs/install/class/installwizard.php
- htdocs/install/class/pathcontroller.php
- htdocs/install/include/common.inc.php
- htdocs/install/include/install_tpl.php
- htdocs/install/page_langselect.php
The secure file inclusion changes left a few stray errors
> Fix include paths in install

- htdocs/class/logger/xoopslogger.php
The message displayed on a fatal exception was not sanitized correctly.
> Sanitize fatal exception message

- htdocs/install/page_tablesfill.php
fix for: https://github.com/XOOPS/XoopsCore25/pull/1355/files/c60d9ed804fe0c8ffb9df28ec5d357f4146120d3
> fix for {$wizard->language}/english/global.php"

- upgrade/index.php
- upgrade/login.php
- add include of core language file user.php to support login
- fatal  exception when checking for OLD 'loginname' column in member handler
> Fix for Upgrade Issues

- htdocs/themes/xbootstrap/modules/pm/pm_viewpmsg.tpl
- htdocs/themes/xswatch4/modules/pm/pm_viewpmsg.tpl
Fix https://github.com/XOOPS/XoopsCore25/issues/1365
> Fix 1365 and php8

- htdocs/class/xoopskernel.php
https://github.com/XOOPS/XoopsCore25/issues/1367
> Undefined_array_key_in_xoopskernel

- htdocs/class/xoopseditor/tinymce5/tinymce5/jscripts/tiny_mce/plugins/xoopsimagemanager/XoopsFormRendererBootstrap4.php
- htdocs/class/xoopsform/renderer/XoopsFormRendererBootstrap4.php
see: https://github.com/XOOPS/XoopsCore25/pull/1379
> moving MAX_FILE_SIZE up

- htdocs/kernel/notification.php
> Made XoopsNotificationHandler::subscribe() return true rather than null.

- htdocs/xoops_lib/modules/protector/oninstall.php
Replaces #1399 (odd git behavior with opposing request changes)
> Fix protector oninstall issue

- htdocs/kernel/avatar.php
- htdocs/kernel/object.php
- htdocs/kernel/online.php
- htdocs/kernel/tplfile.php
See: https://github.com/XOOPS/XoopsCore25/issues/1196
> PhpDoc updates #1196

- upgrade/upd-2.0.18-to-2.3.0/index.php
MySQL changes removing the 'IGNORE' options on INSERT statements in versions 5.7 and above caused upgrade of block_module_link table to fail.
For reference: [https://dev.mysql.com/worklog/task/?id=7395](url)
> Fix issues with upd-2.0.18-to-2.3.0 step

- upgrade/class/Xoops/Upgrade/Smarty3TemplateRepair.php
Any errors show in logger, which is enabled during upgrade.
> Correct error handling in rewriting template

- htdocs/install/include/makedata.php
- htdocs/modules/system/xoops_version.php
1) we included templates that are removed long time ago
2) the routine was trying to read non-admin templates in the /admin folder
> fix for installation issues

- htdocs/kernel/notification.php
See: https://xoops.org/modules/newbb/viewtopic.php?post_id=367102#367102
> fix for email templates in Notifications

- htdocs/modules/profile/changemail.php
> fix for https://github.com/XOOPS/XoopsCore25/issues/1451

- htdocs/install/cleanup.php
See:
XOOPS/issues/1259
install/page_end.php line 40
$install_rename_suffix = uniqid(substr(md5($x = mt_rand()) . $x, -10), true);
> fix for https://github.com/XOOPS/XoopsCore25/issues/1259

- htdocs/modules/system/themes/dark/dark.php
- htdocs/modules/system/themes/dark/language/english/admin.php
- htdocs/modules/system/themes/dark/xotpl/xo_accordion.tpl
- htdocs/modules/system/themes/default/default.php
- htdocs/modules/system/themes/default/language/english/admin.php
- htdocs/modules/system/themes/default/xotpl/xo_accordion.tpl
- htdocs/modules/system/themes/transition/language/english/admin.php
- htdocs/modules/system/themes/transition/transition.php
- htdocs/modules/system/themes/transition/xotpl/xo_accordion.tpl
Adding Smarty version to Admin's System Overview
> add Smarty version

- htdocs/modules/system/class/avatar.php
see https://github.com/XOOPS/XoopsCore25/issues/1463
> fix typed property in avatar.php

- htdocs/class/criteria.php
Addition of a parameter to create a criterion with an empty value.
> fix: https://github.com/XOOPS/XoopsCore25/issues/1464

- htdocs/kernel/block.php
fix for https://github.com/XOOPS/XoopsCore25/issues/1335
> fix https://github.com/XOOPS/XoopsCore25/issues/1335

- htdocs/modules/profile/edituser.php
- htdocs/themes/xbootstrap5/modules/newbb/newbb_index.tpl
**Fix subforum not expanding**
With latest bootstrap version class="in" was replaced by class="show"
**Removed Warning: Undefined array key "subforum"**
by adding a default:false value
> Subforum not expanding

- htdocs/kernel/module.php
- htdocs/modules/profile/xoops_version.php
- htdocs/modules/system/blocks/system_blocks.php
- htdocs/themes/xbootstrap5/config/module_icons.php
- htdocs/themes/xbootstrap5/modules/system/blocks/system_block_mainmenu.tpl
- htdocs/themes/xbootstrap5/style.css
- htdocs/themes/xbootstrap5/theme_autorun.php
For a detailed discussion, see: https://github.com/XOOPS/XoopsCore25/pull/1538
> Adding "id" to sublinks for custom menu icons

- htdocs/userinfo.php
(Fix:https://github.com/XOOPS/XoopsCore25/issues/1561)
> Hide empty userinfo value 
