XOOPS/XoopsCore25

htdocs/class/xoopsform/formselectuser.php, htdocs/modules/system/themes/default/xotpl/xo_tabs.tpl
Full user list was not included when pre-selected values were specified.
Now follows this pattern:
- add anonymous user if $includeAnonymous specified
- add any user(s) specified in $value
- union these with full user list, or the 200 most recently logged in users
The list is cached to reduce thrashing on systems with large user bases.
Also includes fix for issue in an admin area template,
=> Correct issue with FormSelectUser

htdocs/class/database/mysqldatabase.php
In *XoopsMySQLDatabase* the fetchRow(), fetchArray(), fetchBoth(), and fetchOject() methods return the raw value from the actual driver call, for example mysqli_fetch_row(). The return at end of cursor with mysql_fetch_row() was a boolean false. The return in the same condition with mysqli_fetch_row() is null.
Programs checking for a boolean typed false (i.e. `$db->fetchRow() !== false`) could fail in unexpected ways, most commonly as an endless loop. Code that loosely accepts *falsy* values was not affected.
These changes force the return of boolean false on end of data for backward compatibility.
=> Return false on end of data

htdocs/kernel/object.php
This adds a compatibility shim for classes extending XoopsObject, XoopsObjectHandler and XoopsPersistableObjectHandler.
The move away from PHP4 style constructor potentially affects lots of callers. This returns the same name methods to the base classes, but adds a message to reveal the problem.
=> Compatibility shim for XoopsObject

htdocs/install/language/english/welcome.php
In requirements for a WWW Server, add NGINX and drop Roxen mention.
This change is based on current marketshare and trends (and yes, it works.)
=> Minor verbage change in installer

htdocs/modules/profile/class/field.php
=> Not respecting $force

htdocs/modules/profile/admin/visibility.php, htdocs/modules/profile/class/visibility.php
Since the profile_visibility table does not have a single unique column, the *id_as_key* logic will not work correctly. Added a `getAllByFieldId()` method to return an array of arrays of rows, which is what the template was expecting.
With this change, we now get a complete set of visibilities for each field.
Fixes #43
=> Replace getAll() in ProfileVisibilityHandler

htdocs/modules/profile/admin/permissions.php
The admin/permission tab resets to the edit op after every update. This takes away the opportunity for the admin to verify any changed settings post submit without additional action.
This change makes the "op" sticky, so that after submitting changes, the page will display the data that was just changed.
=> Make permission op sticky

htdocs/class/module.textsanitizer.php
Appears we have accidentally had a requirement for ext-mbstring since 2.5.6 :frowning: 
This fixes that, and also adds more complete detection when using mb_detect_encoding().
=> Make mb_* calls conditional on function exists

htdocs/class/model/joint.php
Fixes #92 XoopsModelJoint::getCountByLink bug, from zyspec
=> Fixes issue if id column keyName is common to both tables

htdocs/class/xoopsmailer.php, htdocs/language/english/xoopsmailerlocal.php
Adds a compatibility shim to support calls to XoopsMailer::XoopsMailer() in XoopsMailerLocal implementations. Fixes #115 
The older style XoopsMailerLocal code looks like this:
```
function XoopsMailerLocal()
{
$this->XoopsMailer();
// It is supposed no need to change the charset
$this->charSet = strtolower(_CHARSET);
// You MUST specify the language code value so that the file exists: XOOPS_ROOT_PAT/class/mail/phpmailer/language/lang-["your-language-code"].php
$this->multimailer->SetLanguage("en");
}
```
The old style constructors with the same name as the class are **deprecated** and all support for them [will be removed from PHP](http://php.net/manual/en/language.oop5.decon.php) in the future.
The preferred and fully supported style looks like this:
```
public function __construct()
{ …
```
=> XoopsMailer PHP4 same name constructor shim

htdocs/include/functions.php, htdocs/kernel/object.php
Eliminate some spurious errors reported by some qa tools.
=> Docblock fix for getHandler functions

htdocs/modules/profile/class/profile.php
Fixes #168
Introduced in 3ae590c55ed74b4e9ba56ea56111049d4f06756c when cleaning up method signature issues. Prior to that change, a missing Profile object was created. This change restores that behavior.
=> Bug in ProfileProfileHandler::get()

htdocs/class/xoopsform/formdatetime.php
Implements static constants, SHOW_BOTH, SHOW_DATE and SHOW_TIME, to expand the $showtime parameter to add a time only option.
This replaces #106. A time only element can be specified like this:
```php
new XoopsFormDateTime('', 'name', 15, $time, XoopsFormDateTime::SHOW_TIME);
```
=> XoopsFormDateTime - time only option

upgrade/check_version.php
The instruction to "update system module" presented at the end of the upgrade process is a link, but it is often overlooked. This change makes the instructions into a button with red letters, hopefully driving up the number of smooth successful upgrades.
=> Highlight Update System Module in upgrade

htdocs/class/theme.php, htdocs/themes/xbootstrap/theme.tpl, htdocs/themes/xbootstrap/tpl/slider.tpl
Exemples of values of $xoops_page:
If you are here: http://localhost/htdocs/  ---> $xoops_page = index
If you are here: http://localhost/htdocs/modules/profile/edituser.php  ---> $xoops_page = profile/edituser
$xoops_page to more easily customize themes
=> Add $xoops_page for theme

htdocs/xoops_lib/modules/protector/class/ProtectorFilter.php, htdocs/xoops_lib/modules/protector/class/protector.php, htdocs/xoops_lib/modules/protector/filters_disabled/postcommon_post_language_match.php, htdocs/xoops_lib/modules/protector/filters_disabled/postcommon_post_stopforumspam.php, htdocs/xoops_lib/modules/protector/filters_disabled/postcommon_register_stopforumspam.php, htdocs/xoops_lib/modules/protector/include/postcheck_functions.php
First in a set of protector upgrades
- postcommon_post_language_match.php - post must match language
- postcommon_post_stopforumspam.php - checks sfs before each of the first N posts
- postcommon_register_stopforumspam.php - checks sfs at registration (disable protector's built in when using this one)
=> New Protector Filters

htdocs/install/sql/mysql.structure.sql, upgrade/upd-2.5.8-to-2.5.9/index.php
Length of system a generated session id can be 22-256 characters in PHP 7.1 depending on settings.
=> Handle possible PHP 7.1 session ids

htdocs/class/tree.php
Property $_tree was intended to be private but this intention was not always respected. This restores accessibility to the property with a warning that it is deprecated.
=> BC Patch for XoopsObjectTree

htdocs/modules/system/class/maintenance.php
If directory contains enough entries, glob can fail while gathering entries. Switch to readdir() approach to reduce memory demand. Re: #261
=> Remove glob call in \SystemMaintenance::CleanCache

htdocs/include/mimetypes.inc.php
The .csv extension is missing! The current system is not very practical to add a mimetype. For xoops 2.6 you have to change that.
=> add .csv mimetypes

htdocs/modules/system/templates/admin/system_blocks_item.tpl
Show block number after cloned blocks in blocks administration. This is to help identify blocks if the name was not changed when cloned.
Fixes #275
=> Add indication on cloned blocks

htdocs/class/tree.php
Re: #292
Adds makeSelectElement() method that returns a XoopsFormSelect object. This allows for themed appearance of the tree select.
Deprecates makeSelBox() which build its own form code and returns it as a string.
=> Use XoopsFormSelect in XoopsObjectTree

htdocs/modules/system/templates/system_comment.tpl, htdocs/readpmsg.php
Images, such as images/icons/reply.gif and delete.gif, are hardcoded with english text. They appear quite dated and impede localization. With this change, these are no longer referenced in active core.
=> Removing graphic images with english text

htdocs/modules/system/blocks/system_blocks.php
Fixes #309 - an edge case where top posters block is used on an unused site.
=> Supress zero post users

htdocs/themes/xbootstrap/modules/system/blocks/system_block_siteinfo.tpl
Override system_block_siteinfo.tpl template to avoid legacy conflicts. Fixes #308 
Main issue is the css class "collapse" used on the table. This has a much different meaning in ANY bootstrap based theme.
The intended definition comes from /xoops.css
```
.collapse {
border-collapse: collapse;
}
```
Changing the base template could break layout in non-bootstrap themes, so a new theme override template is added. Other bootstrap themes may want to adopt a similar solution.
=> Add bootstrap compatible template

htdocs/kernel/module.php, htdocs/xoops_lib/modules/protector/include/precheck.inc.php, htdocs/xoops_lib/modules/protector/xoops_version.php
Under PHP 7.1 there is an error:
> Notice: A non well formed numeric value encountered in file /kernel/module.php line 78
This appears to come from protector's use of a version.txt file it reads to obtain the actual version number. That file has a line feed at the end, and the entire contents of the file, including the line ending, is assigned to the $modversion['version'] key in xoops_version.php. That can result in the notice when a XoopsModule object for protector is accessed.
Change to both protector and XoopsModule to cast the version as float, which silently swallows the offending whitespace.
=> Error from protector in PHP 7.1

htdocs/class/xml/saxparser.php
Let PHP handle freeing resources.
- unset($this) is a fatal error in PHP 7.1 (never was a good idea)
- __destruct() is called automatically by PHP when appropriate
=> Error in class management

htdocs/install/class/pathcontroller.php, htdocs/install/language/english/install.php, htdocs/install/page_pathsettings.php, htdocs/mainfile.dist.php
The domain of a cookie effects which subdomains the cookie will be sent to.
Historically, the XOOPS_COOKIE_DOMAIN constant has been determined by an algorithm, which in some cases produced invalid results. Changing it required digging into code. The constant will now be explicitly defined in mainfile.php and exposed as a configurable option during the install.
=> Add cookie domain to install

htdocs/imagemanager.php, htdocs/modules/system/templates/system_imagemanager2.tpl
A FINEUPLOADER_DEBUG key in $_REQUEST will turn on debugging output from Image Manager.
Example:
`/imagemanager.php?target=message&op=upload&imgcat_id=1&FINEUPLOADER_DEBUG`
Also, add js console logging of error messages from handlers.
=> Debug option for fine uploader

htdocs/class/captcha/recaptcha/recaptchalib.php
Switches the default setting for recaptcha api to use SSL. Best practices dictate that if a resource is available over https, it should be fetched that way.
There should be no BC issues from this change. Also worth noting that recaptcha is no longer supported by Google. Switching to Recaptcha2 is recommended.
=> Use SSL by default for recaptcha

htdocs/class/smarty/xoops_plugins/function.xoInboxCount.php
Adds a total parameter used to assign the number of messages in the inbox to a smarty variable. Full backward compatibility is maintained.
xoInboxCount lets templates access private message inbox statistics for the current user
Example: `<{xoInboxCount assign='unread_count' total='inbox_total'}>`
Both assign and total parameters are optional. If neither is specified the unread count is displayed.
- assign = variable name to assign with the current unread message count
- total  = variable name to assign with the current inbox total
=> smarty xoInboxCount plugin enhancement

htdocs/themes/xswatch/css-dark/xoops.css, htdocs/themes/xswatch/css-light/xoops.css, htdocs/themes/xswatch/css/xoops.css
Re: #399
The system jGrowl styles can now be overridden by the theme's css, so this change tweaks it a bit for xswatch.
=> Match jGrowl to theme in xswatch

htdocs/install/class/pathcontroller.php, htdocs/install/include/common.inc.php, upgrade/checkmainfile.php, upgrade/class/control.php, upgrade/index.php, upgrade/language/english/upgrade.php, upgrade/upd-2.5.8-to-2.5.9/index.php
Fixes a few issues reported during in the field use.
- Intercept fatal error or unhandled exception to issue message regardless of other settings
- make sure the entered cookie domain is valid
- rewrite mainfile.php and data/secure.php as part of 2.5.9 upgrade
- attempt to disable obsolete and problematic "legacy" admin theme
=> Installer and Upgrader tweaks

htdocs/modules/profile/admin/user.php
Restore add user form to default view on admin/user.php
This returns to the behavior which was consistent thru 2.5.6 which seems to have been inadvertently changed.
Fixes: #397
=> Add user issue

htdocs/class/xoopsform/formselectuser.php
Script added via addScript() which also adds script tags. This can result in in the CDATA closing sequence "//]]>" being introduced in the display.
This was what the rendered page contained:
```
<script type="text/javascript">
//<![CDATA[
<script type='text/javascript'>
function addusers(opts)
{
// ...
}
</script>
//]]></script>
```
Example of the visual defect shown in Profile module admin User page (using Chrome 56.0.2924.87)
=> Remove redundant script tags

htdocs/class/xoopsform/formselectuser.php
JS to add users was not being added in pmlite as xoTheme was not set.
=> Handle no theme case in XoopsFormSelectUsers

.gitignore, htdocs/class/theme.php
Issue with paths on Windows affecting $xoops_page theme variable. This cause the xBootstrap slider to fail, among other less obvious things.
Fixes #415
=> Normalize paths

htdocs/modules/profile/class/field.php
It seems there was a change introduced in Xoops 2.5.2 that changed the getVar behavior for arrays on XoopsObject.
I was able to reproduce the bug and this change fixed it for me. I also tested radio buttons and changing datatype from array to integer and had no problems.
=> Fix issue #410 for profile module: select fields not showing.

htdocs/themes/xbootstrap/README.md, htdocs/themes/xbootstrap/modules/extgallery/extgallery_public-photo.tpl, htdocs/themes/xbootstrap/modules/news/news_article.tpl, htdocs/themes/xbootstrap/modules/publisher/publisher_item.tpl, htdocs/themes/xbootstrap/modules/tdmdownloads/tdmdownloads_singlefile.tpl, htdocs/themes/xbootstrap/modules/xoopstube/xoopstube_singlevideo.tpl, htdocs/themes/xbootstrap/tpl/shareaholic-script.tpl, htdocs/themes/xswatch/modules/extgallery/extgallery_public-photo.tpl, htdocs/themes/xswatch/modules/news/news_article.tpl, htdocs/themes/xswatch/modules/publisher/publisher_item.tpl, htdocs/themes/xswatch/modules/tdmdownloads/tdmdownloads_singlefile.tpl
Re #433 
Previously, social sharing links through Shareaholic were automatically enabled. These are now optional and disabled by default. To enable Shareaholic support follow these steps:
- Visit https://shareaholic.com to create an account and register your site
- Take note of the *Site Id* code Shareaholic assigns to your site
- Open the template file *themes/xbootstrap/tpl/shareaholic-script.tpl* in your editor
- Replace the *n/a* in this line `<{assign var='siteId' value='n/a'}>` with the *Site Id* Shareaholic assigned to you, andd save the file
You can customize how Shareaholic interacts with your site in the Site Tools Dashboard on Shareaholic.com. You may want to create an Inline App Location on that page to customize the Share Buttons. These will show in templates such as …
=> Change in Shareaholic support

htdocs/modules/pm/viewpmsg.php
Re: #438 
Core uses `include_once $GLOBALS['xoops']->path('class/pagenav.php');` in all cases except this one.
=> Include once

htdocs/register.php
Researching issue #429 and found several by reference object assignments (quietly ignored since only anonymous can use it.)
While in the code, added input constraints as suggested by Cedric. I can't pinpoint an exact scenario, but there are a lot of paths in the register script. Limiting GET method requests to the intended set of  operations sounds like a good idea.
=> By ref errors

htdocs/class/libraries/composer.dist.lock, htdocs/class/libraries/vendor/composer/installed.json, htdocs/class/libraries/vendor/geekwright/regdom/data/public_suffix_list.dat, htdocs/class/libraries/vendor/xoops/xmf/src/Xmf/Metagen.php
- Xmf\Metagen::generateSeoTitle issue
Addresses https://github.com/XOOPS/xmf/issues/26
=> Library updates

docs/lang_diff.txt, htdocs/install/language/english/finish.php
Re: #466 
The links for the module repository and theme gallery are stale. There are efforts to replace them in the new xoops.org site, but those are not complete at this time. For now, the links were replaced with more generic advice to seek modules and themes on xoops.org.
=> Remove stale links

htdocs/class/libraries/composer.dist.lock, htdocs/class/libraries/vendor/composer/installed.json, htdocs/class/libraries/vendor/symfony/yaml/Escaper.php, htdocs/class/libraries/vendor/symfony/yaml/Exception/ParseException.php, htdocs/class/libraries/vendor/symfony/yaml/Inline.php, htdocs/class/libraries/vendor/symfony/yaml/Parser.php, htdocs/class/libraries/vendor/symfony/yaml/Tests/InlineTest.php, htdocs/class/libraries/vendor/symfony/yaml/Tests/ParserTest.php, htdocs/class/libraries/vendor/symfony/yaml/phpunit.xml.dist
- xoops/xmf to V1.2.8
- symfony/yaml to v2.8.20
=> Upstream library updates

htdocs/Frameworks/moduleclasses/moduleadmin/moduleadmin.php, htdocs/modules/pm/xoops_version.php, htdocs/modules/profile/xoops_version.php, htdocs/xoops_lib/modules/protector/xoops_version.php
- Modules included in core have trailing '/' in URL used in About page, leading to 404 on gnu.org
- `\ModuleAdmin::renderAbout()` always adding 'http://' to *license_url* and *website* keys, even if already present
=> Fix broken license_url in core modules

htdocs/class/libraries/vendor/xoops/xmf/src/Xmf/Module/Helper/Permission.php
File was accidentally omitted from PR #475
=> Missing file update in XMF

htdocs/modules/pm/class/message.php
Error: TypeError: Argument 1 passed to PmMessageHandler::sendEmail() must be an instance of XoopsPrivmessage, instance of PmMessage given, called in /modules/pm/readpmsg.php on line 45 in file /modules/pm/class/message.php line 157
=> Error in email forward

htdocs/modules/system/themes/default/xotpl/xo_accordion.tpl, htdocs/modules/system/themes/transition/xotpl/xo_accordion.tpl, htdocs/modules/system/themes/zetadigme/xotpl/xo_accordion.tpl
Fixes #494 
We really need to work out a plan to rebuild some missing sections and functionality on xoops.org, but this is not the forum to develop a consensus on that. These changes just makes the links relevant and contemporary.
=> Freshen Links

htdocs/modules/system/class/cookie.php, htdocs/modules/system/header.php
Class is not used and contains errors. Will remove in next XOOPS version.
=> Deprecate system module Cookie class

htdocs/class/theme.php
This reverses the current search order, so that now it will look for theme.tpl, and if not found use theme.html.
Fixes #504
=> Theme template search order

htdocs/modules/system/blocks/system_blocks.php
If $option[2] is not set, default to a value of 3 in b_system_themes_show() and b_system_themes_edit().
Fixes issue #502
=> Provide default value

htdocs/modules/system/themes/transition/transition.php
Added missing tooltip.js used in 'transition' Control Panel GUI.
XOOPS_URL/admin.php
=> added missing tooltip.js

htdocs/class/uploader.php
In XoopsMediaUploader, there is an option, $allowUnknownTypes, that could allow a malicious mime-type supplied in an HTTP request to be returned directly to the caller. Without further processing by the caller, a carefully crafted mime-type could be used to facilitate other malicious actions.
This change checks the structure of the mime-type, and will always reject any upload attempted with a non-conforming content-type specified (i.e. containing script code.)
Fixes #524
=> Sanitize Mime-Type

htdocs/Frameworks/moduleclasses/moduleadmin/moduleadmin.php
The introduction of version 2.5.10 broke the moduleadmin class version checking for "min_xoops."
This change uses PHP's version_compare() to test the XOOPS version.
=> Use semver rules to check min_xoops

htdocs/xoops_lib/modules/protector/class/protector.php
Protector::purgeCookies() assumed global $xoopsConfig is available, but it can be invoked in response to core.include.common.start event.
Secondary issue, many of the hard coded names were no longer correct, and new ones have been added.
This change attempts to delete *all* cookies sent to the page.
Re: #551
=> Fix purgeCookies()

htdocs/class/smarty/xoops_plugins/modifier.truncate.php
This plugin overrides the standard Smarty modifier.truncate.php and is multi-byte safe, allowing use with UTF-8 output.
=> UTF-8 ready truncate for Smarty

htdocs/class/logger/xoopslogger.php
Automatically add a trace to the message when addDeprecated() is invoked. This should make it much easier for the programmers to track down and eliminate calls to deprecated functions/methods.
=> Add mini-trace to addDeprecated()

htdocs/kernel/member.php
$ret not defined as an array in getGroupsByUser() method.
=> Fix uninitialized variable

htdocs/class/smarty/xoops_plugins/modifier.truncate.php, htdocs/include/comment_view.php
Returning empty string instead of un-truncated short strings.
=> Fix XOOPS truncate plugin

htdocs/modules/profile/index.php
Reports indicate on some circumstances, the system_userform.tpl is not properly displayed. This check is suspect, and could cause issues under the right circumstance.
Re: #559
=> Use standard xoopsUser check

htdocs/class/theme.php
Exposing the theme and templating objects to theme_autorun.php allows useful interactions, such as defining Smarty variables.
=> Expose xoTheme and xoopsTpl for theme_autorun.php

htdocs/xoops_data/protector/index.html, htdocs/xoops_lib/modules/protector/class/protector.php
Protector requires write access to xoops_lib/modules/protector.
XOOPS_VAR_PATH is always intended to be writable so it is better suited to be used for files like those that protector uses.
This changes protector's configs to xoops_data/protector.
Note: existing protector configs are not moved in this change. The file names remain the same, so if needed (i.e. IP ban lists) the files can be moved manually.
=> Move protector data to xoops_data

htdocs/class/model/write.php
In the current internet environment it seems that using the installed protocol as the 'default' would be better than using http:  this allows links to URLs on the same site to maintain SSL.
=> Change hard coded http: to use XOOPS_PROT for URLs

htdocs/kernel/object.php
Similar to #568 - change the installed protocol to be the 'default' would be better than forcing http: to allow links to URLs on the same site to maintain SSL.
=> Another hard coded http: to use XOOPS_PROT for URLs

htdocs/class/smarty/xoops_plugins/modifier.truncateHtml.php
Truncates HTML to a number of words preserving valid markup.
The modifier can take two optional arguments
- count - an integer, number of words to show, default 80
- etc - a string appended to the truncated HTML, default UTF-8 ellipsis
Examples:
```
<{$body|truncateHtml:100}>
<{$body|truncateHtml:40:'...'}>
```
=> Add Smarty modifier truncateHtml

htdocs/ajaxfineupload.php, htdocs/modules/system/templates/admin/system_avatars.html, htdocs/modules/system/templates/admin/system_avatars.tpl, htdocs/modules/system/templates/admin/system_images.html, htdocs/modules/system/templates/admin/system_images.tpl, htdocs/modules/system/templates/system_imagemanager2.html, htdocs/modules/system/templates/system_imagemanager2.tpl
JWT is now passed as a body parameter named 'Authorization' rather than as a HTTP header. The headers are scrubbed in some hosting situations causing uploads to fail.
Callers are adjusted to replace:
```
customHeaders: {
"Authorization": "Basic <{$jwt}>"
}
```
with:
```
params: {
"Authorization": "<{$jwt}>"
}
```
=> Pass JWT for ajaxfineupload in post, not header

htdocs/index.php
Prevents infinite redirect loop when a registered user does not have access permission to the start page module.
Fixes #590
=> Always redirect to user.php on no permission

htdocs/class/criteria.php, htdocs/install/include/functions.php, htdocs/install/sql/mysql.structure.sql
The changes provide basic compatibility with MySQL 8.0 in XoopsCore25
*Please note* that there are some actions required outside of XOOPS to configure MySQL 8 to be compatible with PHP. For more information, see: 
https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html
https://mysqlserverteam.com/upgrading-to-mysql-8-0-default-authentication-plugin-considerations/
http://php.net/manual/en/ref.pdo-mysql.php
> PHP: the PDO_MySQL and ext/mysqli extensions do not support caching_sha2_password. In addition, when used with PHP versions before 7.1.16 and PHP 7.2 before 7.2.4, they fail to connect with default_authentication_plugin=caching_sha2_password even if caching_sha2_password is not used.
=> Basic support for MySQL 8.0

htdocs/ajaxfineupload.php, htdocs/modules/system/class/fineuploadhandler.php
Reviewing fineuploader support for security and operational issues resulted in the following changes:
- allow fully qualified namespaced autoloading handler name
- require handler to be specified (removed default)
- require allowedMimeTypes property to be set in handlers
- disallow direct use of system fineuploadhandler class (now abstract)
- removed arbitrary handler property setting in ajaxfineupload endpoint
=> Fineuploader Review

htdocs/class/xoopslists.php
Fixes bug discussed in https://github.com/XoopsModules25x/tdmdownloads/issues/60
=> Recognize jpeg extension in getImgListAsArray()

htdocs/modules/profile/include/install.php
By default, these will not show in the profile module unless the admin enables them. This was the original intention with change that went in with 2.5.9.
This only affects new installs of the profile module.
Core user management remains unchanged.
=> Hide ICQ, AIM, YIM, MSNM fields on new installs

htdocs/Frameworks/moduleclasses/moduleadmin/moduleadmin.php
Note PHP Manual:
Special version strings such as alpha and beta are case sensitive. Version strings from arbitrary sources that do not adhere to the PHP standard may need to be lowercased via strtolower() before calling version_compare().
=> Add strtolower()

htdocs/kernel/object.php
This method is not in common use and encourages potentially dangerous bad habits.
=> Deprecate \XoopsObject::setFormVars()

htdocs/modules/system/themes/default/js/tooltip.js, htdocs/modules/system/themes/transition/js/tooltip.js, htdocs/modules/system/themes/zetadigme/js/tooltip.js, htdocs/modules/system/themes/zetadigme/xotpl/xo_toolsbar.tpl
Escape tooltip text in admin themes. Also, remove HTML styling in zetadigme admin theme.
=> Escape Tooltip Text

htdocs/class/uploader.php
=> Handle negative ini sizes

htdocs/class/xoopsform/renderer/XoopsFormRendererBootstrap3.php, htdocs/class/xoopsform/renderer/XoopsFormRendererBootstrap4.php
Effects height, font and color controls in dhtmleditor rendering for Bootstrap v3 and v4.
=> Replace glyphicon based controls with font-awesome

htdocs/class/smarty/xoops_plugins/function.xoMemberInfo.php
XoopsUser object is always populated, so there is no need to cache.
Fixes #735
=> Remove broken caching

htdocs/class/mail/xoopsmultimailer.php, htdocs/install/sql/mysql.data.sql, upgrade/upd-2.5.9-to-2.5.10/index.php, upgrade/upd_2.5.10-to-2.5.11/index.php
Correct issues identified while researching a user issue.
- XoopsMultiMailer extends phpMailer, but does not call parent::__construct()
- phpMailer has qmail support, but XOOPS configuration option is missing
=> Mail Tweaks

htdocs/class/smarty/xoops_plugins/function.xoInboxCount.php
When working with pm's, the counts provided by the xoInboxCount Smarty plugin will always be current. Otherwise, the cache will be updated every 60 seconds. This should provide a less confusing user experience when reading messages.
Re: #738
=> Refresh inbox count cache when using pm programs

htdocs/class/module.textsanitizer.php
Addresses #741 
This adds a check in MyTextSanitizer::displayTarea() to see if it contains HTML markup.
If it does, it will turn off the call to nl2Br() that adds the br tags on blank lines.
If you can, please test this with existing content and report any undesirable side effects.
(Also includes some deprecation tag cleanup.)
=> Skip nl2Br() if html detected in MyTextSanitizer::displayTarea()

htdocs/class/template.php
(PHP 7.4 complained about missing _LANGCODE and _CHARSET)
=> include global.php in template.php 

htdocs/class/database/mysqldatabase.php, htdocs/xoops_lib/modules/protector/class/ProtectorMysqlDatabase.class.php
Alternate to #753
- Declare XoopsMySQLDatabase abstract
- Declare XoopsMySQLDatabase::query()
- Correct return type in dockblock of query() and queryF() methods
=> Type fixes in XoopsMySQLDatabase

htdocs/modules/system/preloads/core.php
This change makes the loading of jquery for jgrowl support conditional on jQuery not being defined.
Previously, when jgrowl was loaded it replaced any previously loaded jquery instance with a new one. This resulted in some interference with other code, such as bootstrap, that had been loaded earlier in the page.
=> Do not load jquery.js if already loaded

htdocs/class/theme_blocks.php
Suppress display of block titles starting with `// `.
The display of a block title can be suppressed by leaving the title field blank, but this makes it difficult to identify blocks when editing in the admin section.
This change allows "commenting" out a title by starting it with a slash-slash-space sequence. Blocks with a title starting with this sequence will be displayed as if their title was blank.
=> Allow comment instead of blank title

htdocs/class/xoopsform/renderer/XoopsFormRendererBootstrap3.php, htdocs/class/xoopsform/renderer/XoopsFormRendererBootstrap4.php, htdocs/class/xoopsform/renderer/XoopsFormRendererLegacy.php
Fixes #764 
Several issues found:
- The localized format date is directly used to instantiate a js Date object, and those localized formats are not supported in that context.
- There seems to be a bug that effects the preferred ISO format, causing calendar.js to be off by one day back(?)  The generally supported mm/dd/yyyy seems to work correctly.
Helpful reference: https://www.w3schools.com/js/js_date_formats.asp
=> Remove locale specific date format for calendar.js

docs/lang_diff.txt, htdocs/class/xoopsform/renderer/XoopsFormRendererBootstrap4.php, htdocs/language/english/global.php
Re: #778
- add "dropdown-item" class to typography controls, adds missing padding
- change _FONT, _SIZE and _COLOR constants to mixed case
Note that _FONT, _SIZE and _COLOR constants are in htdocs/language/english/global.php,
so changes in other languages are dependent on updated language files.
=> Correct issues in dhtmltextarea

htdocs/admin.php, htdocs/language/english/backend.php
- use https and no "www." for xoops.org feeds
- give priority to feed(s) in htdocs/language/.../backend.php
- present multiple feeds sequentially, not merged
Re: #782
=> Tweak feeds used in XOOPS News in admin.php

htdocs/admin.php, htdocs/class/snoopy.php, htdocs/class/xoopshttpget.php, htdocs/class/xoopsload.php
**Adds class XoopsHttpGet**
This class is used to retrieve the response from an http(s) request to a URL. It is replacing "Snoopy" that has been used for fetching rss feeds in the administration area.
For proper operation, it requires the curl PHP extension, or alternately that the ini settiing 'allow_url_fopen' is enabled.
**Deprecates class Snoopy**
This class will be removed in a future version of XOOPS. Developers are encouraged to remove any dependencies on this class.
Issues with Snoopy were reported in #782
=> Add XoopsHttpGet, deprecate Snoopy

htdocs/modules/system/blocks/system_blocks.php
Notice: Undefined index: modules in file
...xoops_data/caches/smarty_compile/...system_block_mainmenu.tpl.php
The common template line is:
`<{foreach item=module from=$block.modules}>`
A rare circumstance, but simple fix initializing 'modules' key.
=> Error when no modules installed

htdocs/modules/profile/admin/field.php, htdocs/modules/profile/include/forms.php, htdocs/modules/profile/language/english/admin.php, htdocs/modules/profile/xoops_version.php
Options taken from language files cannot be changed after installing the profile module.
This change adds an edit link to the form for any field that has options such as a select field. The edit screen presented allows updating the option text only, not the values.
Initial report here:
https://xoops.org/modules/newbb/viewtopic.php?topic_id=78808
=> Add options text editing to profile field edit

htdocs/class/theme.php, htdocs/install/include/makedata.php, htdocs/install/language/english/finish.php, htdocs/modules/system/language/english/help/preferences.html, htdocs/themes/xbootstrap/theme.tpl, htdocs/themes/xswatch/theme.tpl, htdocs/themes/xswatch4/theme.tpl
Re: #846 - Adds macro substitutions for {X_SITEURL} and {X_YEAR}
In *Preferences -> Meta Tags and Footer* process substitutions for {X_SITEURL} and {X_YEAR} only in 'footer' and 'meta_copyright' fields.
- {X_SITEURL} is replaced by the site URL
- {X_YEAR} is replaced by the current year
=> Add macro substitutions for {X_SITEURL} and {X_YEAR}

htdocs/class/smarty/Smarty_Compiler.class.php
see: https://github.com/smarty-php/smarty/pull/544
=> allow StdClass to be cast to array when compiling foreach

htdocs/modules/system/admin/maintenance/main.php, htdocs/modules/system/templates/admin/system_maintenance.html, htdocs/modules/system/templates/admin/system_maintenance.tpl
- **Changed behavior** in XoopsFormRadioYN value (value of empty string is not considered NO) - change to 0
- provide default value for possibly undefined variable in template
=> PHP 8 issues in system maintenance

htdocs/xoops_data/caches/smarty_cache/index.html, htdocs/xoops_data/caches/smarty_compile/index.html, htdocs/xoops_data/caches/xoops_cache/index.html
Adding back index.html files. Note these are not index.php as the different extension is used in \SystemMaintenance::clearDirectory and is helpful when clearing manually as well.
Re: #890
=> Restore missing xoops_data/caches directories

htdocs/modules/system/templates/admin/system_images.html, htdocs/modules/system/templates/admin/system_images.tpl
Truncate long image names that break the display
=> Clean up image manager display

htdocs/themes/xswatch4/tpl/content-zone.tpl, htdocs/themes/xswatch4/tpl/leftBlock.tpl, htdocs/themes/xswatch4/tpl/rightBlock.tpl
Please test the original xswatch4 and this on md / sm and xs mode.
I think it's better with theses modes.
=> Responsive xswatch4

htdocs/modules/pm/class/message.php
An inbox count issue is triggered when:
- "From" user saves a copy of a PM to outbox during send
- "To" user deletes PM without reading it
This results in the "To" user's inbox count being inaccurate until the outbox copy is deleted.
This change marks the message read when it is marked for deletion by the recipient.
Replaces #927
=> Mark deleted PM as read

docs/changelog.250.txt, htdocs/install/page_modcheck.php
Extension is enabled by default but can be disabled in some installations.
See #888
=> Require fileinfo PHP extension during install

htdocs/include/common.php
Unclosed comment introduced in #851, luckily harmless since it was followed by another comment.
=> Fix unclosed comment

htdocs/modules/system/admin/modulesadmin/main.php
some modules have it like $modversion['version'] = '2.5.1';
=> fix for version number as string

htdocs/class/template.php, htdocs/include/common.php
Adds triggers of two new events.
**core.include.common.auth.success**
Event is triggered when the establishment, or re-establishment, of the current user is complete.
At this point valid security decisions can be made based on the state of the current user.
**core.class.template.new event**
This event is triggered when a new XoopsTpl (an extended Smarty object) is created. This allows customization of the Smarty environment from within a module.
One possible use would be to support a module based plugin library. An simplified example event listener:
```php
public static function eventCoreClassTemplateNew($arg)
{
$smartyObject = $arg[0];
$smartyObject->plugins_dir[] = __DIR__;
}
```
=> Add two new events

htdocs/class/model/read.php
\XoopsModelRead::getAll() fails to handle a return of false from a database query(). It then attempts to use the false value as a result set which now causes a nasty failure.
As there is no documented failure return mechanism, the return in the case of failure is now an empty array. This may not be ideal, but should not break compatibility.
Also, removed some dead code regarding an $orderSet variable.
=> Recognize error return from db->query()

htdocs/modules/profile/templates/profile_userinfo.tpl, htdocs/themes/xbootstrap/modules/profile/profile_userinfo.tpl, htdocs/themes/xswatch/modules/profile/profile_userinfo.tpl, htdocs/themes/xswatch4/modules/profile/profile_userinfo.tpl
Issue involves form element inside a form element. Noticeable when self_delete is enabled. Besides the html error, the
form buttons from the rouge forms, such as if delete_user is enabled, are squashed into the surrounding buttons degrading
visual appearance.
Forms within forms had propagated from the module default template to all included themes.
=> Bad form in profile_userinfo.tpl

htdocs/xoops_lib/modules/protector/filters_disabled/postcommon_post_htmlpurify4everyone.php, htdocs/xoops_lib/modules/protector/filters_disabled/postcommon_post_htmlpurify4guest.php
These were missed in an earlier move of protector configs from xoops_lib to xoops_data.
=> Protector config cache for htmlpurifier written to xoops_lib, should go to xoops_data

htdocs/include/site-closed.php, htdocs/themes/default/modules/system/system_siteclosed.tpl, htdocs/themes/xbootstrap/modules/system/system_siteclosed.tpl, htdocs/themes/xswatch/modules/system/system_siteclosed.tpl, htdocs/themes/xswatch4/modules/system/system_siteclosed.tpl
Any error message from an attempted login would normally be displayed by jgrowl, but that function is not included in the minimal site closed page templates. (With jgrowl redirects turned off, the interstitial page does show with any message.)
This change assigns any redirect message to $redirect_message in include/site-closed.php. It can then be utilized in the system_siteclosed.tpl template as desired.
All such templates included in XoopsCore25 now display these messages.
Fixes #901
=> Make $redirect_message available in system_siteclosed.tpl

htdocs/include/common.php, htdocs/themes/default/modules/system/system_redirect.tpl, htdocs/themes/default/modules/system/system_siteclosed.tpl, htdocs/themes/xbootstrap/modules/system/system_siteclosed.tpl, htdocs/themes/xswatch/modules/system/system_siteclosed.tpl, htdocs/themes/xswatch4/modules/system/system_siteclosed.tpl
If for any reason the $xoopsConfig['debugLevel'] is not set the default was 0? A default of 2 (admin group) seems more appropriate.
=> Wrong default for debugLevel configuration

htdocs/themes/xswatch4/tpl/centerFooter.tpl, htdocs/themes/xswatch4/tpl/leftBottom.tpl, htdocs/themes/xswatch4/tpl/leftFooter.tpl, htdocs/themes/xswatch4/tpl/rightBottom.tpl, htdocs/themes/xswatch4/tpl/rightFooter.tpl
Modifed "col-sm-x" into "col-12"  for Footer (L / C / R) and for BottomBlock (L / R ).
Now, it's readable in mode smaller than md.
#955
=> Responsive blocks

htdocs/install/include/common.inc.php, htdocs/install/include/createconfigform.php, htdocs/install/include/functions.php
Before mainfile.php is written, XOOPS_ROOT_PATH is defined based on the filesystem location of installer. The forms used to collect install data use textsanitizer in some situations. Textsanitizer now uses XOOPS_VAR_PATH in locating config files, and in this case, before that define is established.
The only method used is MyTextSanitizer::htmlSpecialChars so this commit replaces those calls with calls to a work-alike local function.
=> Errors using XOOPS_VAR_PATH early in install

htdocs/class/smarty/xoops_plugins/resource.db.php
Re: #974
Example: override system_confirm.tpl in admin transition theme with template here:
`modules/system/themes/transition/modules/system/system_confirm.tpl`
Override of block templates in the directory:
`modules/system/themes/transition/modules/system/blocks/`
Override of admin templates remains unchanged in the directory:
`modules/system/themes/transition/modules/system/admin/`
=> Allow for override of any template in admin themes

htdocs/class/template.php
Templates used in admin themes were being compiled under the user-side theme name, with nothing to differentiate them. This will use the admin theme name, prefixed with 'cp-' to insure that the compiled templates are properly represented in the caches.
=> Cpanel aware smarty compile id's

htdocs/xoops_lib/modules/protector/admin/admin_header.php, htdocs/xoops_lib/modules/protector/admin/center.php
center.php actually rendered the pagenav before it did the typical admin xoops_cp_header() that establishees it as a control panel themed page.
=> Fix pagenav in protector center

htdocs/kernel/online.php
If a user comes to the xoops site, he is registered as anonymous. The user logs in and a new entry is added to the database. The problem is that this person appears as anonymous and members at the same time (just look at the ip addresses to see that they are the same). This patch is used to update the status of a user who connects, it is no longer counted as anonymous.
=> Fix bug with bloc on-line.

htdocs/kernel/online.php
Rework on #1005  -- Sorry, my bad. :frowning: 
On revisiting, the original change was too late. By the time the newly logged in user has a row in the online table, it is too late to clean up. At that point, just determining there is a problem becomes complex.
Instead, this tries to delete the anonymous user row in the online table that the newly signed in user created before inserting the new row for the user.
=> Delete phantom anonymous entry in online left when user logs in

htdocs/themes/xswatch4/language/english/main.php, htdocs/themes/xswatch4/modules/system/blocks/system_block_online.tpl, htdocs/themes/xswatch4/modules/system/system_misc_online.tpl
Since Richard modify misc.php, we can use overloaded templates.
Improvement :
system_bloc_online:
- Full Bt4
- Add icons
- Icons depends number (<2 and >1)
- Icons color depend groups (all, anonymous, members)
- Text depends number
- Add icon for "more"
system_misc_online:
- Full BT4
- All redesigned
- No avatar for anonymous
- No avatar for members if they have not (space saving)
- Icons for IP and date
- Add a cycle value for background colors
- Large button to close window
- More readable if you expand larger windows size
=> Bootstrap 4 online templates for xswatch4

upgrade/upd_2.5.10-to-2.5.11/index.php
During upgrade, if a directory is removed (i.e. an unwanted theme) don't try to scan.
=> Skip scan if directory is not present

htdocs/class/database/mysqldatabase.php, htdocs/install/page_dbconnection.php, htdocs/xoops_lib/modules/protector/class/protector.php
The default value for this setting is changing in PHP 8.1. With the current default, errors are reported by returning false, while the future default will be to throw an exception.
Explicitly declaring the value we use now, even though it is the default, will prevent future problems.
=> Explicitly set default mysqli_report(MYSQLI_REPORT_OFF)

docs/lang_diff.txt, htdocs/admin.php, htdocs/language/english/admin.php
Display a proper message if Xoops News in admin cannot function.
Fixes #1096
=> Display warning if xml extension not available

htdocs/class/database/database.php, htdocs/class/database/mysqldatabase.php
Examine a variable and determine if it is a valid result set from the database engine.
Example:
```php
$result = $xoopsDB->query($sql);
if ($result, $xoopsDB->isResultSet($result)) {
// process result
}
```
Fixes #1117
=> Add \XoopsDatabase::isResultSet()

htdocs/themes/xswatch4/modules/profile/profile_userinfo.tpl, htdocs/themes/xswatch4/modules/system/system_search.tpl
- I added an "automatic" image overload mode.
If image overloading is present then use it otherwise use the default image
Exemple to overload the search image for xmnews: ![xmnews_search](https://user-images.githubusercontent.com/5336960/141340330-a7497514-e8fa-4973-b32a-eeb4028d554d.png) => ![xmnews_search](https://user-images.githubusercontent.com/5336960/141340161-c6ac216f-1a96-493d-ab91-67c2337f294e.png)
Add /themes/xswatch4/modules/xmnews/assets/images/xmnews_search.png (new logo ![xmnews_search](https://user-images.githubusercontent.com/5336960/141340161-c6ac216f-1a96-493d-ab91-67c2337f294e.png))
- I modernized the page with a presentation by module in cards
I also changed the location of some elements in order to have an optimal reading
- I replaced "<< Previous Next >>" with nice …
=> bt4 search for xswatch4

htdocs/include/findusers.php
Includes and replaces #1131
- Remove query mode
- tweak Xmf\Request() calls
- use database escape() ro replace $ts->addSlashes()
- remove aim, yim, icq and msnm selectors
=> Review filter and escape in findusers 

htdocs/modules/system/admin/modulesadmin/modulesadmin.php
This is to make it consistent with module installation behavior. It makes also easier to click on the image of the activated module to go to its admin
When module is deactivated then, of course, the image should not have the link
I'm using it in my  https://github.com/mambax7/moduleinstaller
=> add link to image of an activated module

htdocs/class/module.textsanitizer.php
For better security, the makeClickable() method now limits the schemes it considers to:
- raw email address
- https/http urls
- sftp/ftp urls
(Note: most browsers have stopped handling ftp urls directly)
=> A less aggressive \MyTextSanitizer::makeClickable()

htdocs/modules/system/class/maintenance.php
After cleaning caches, the now recreated index.php files show as changed in git comparisons. This restores the proper EOL so files match.
=> Add trailing end of line

htdocs/modules/system/class/menu.php
Was mentioned on in #1133 but not properly dealt with.
The menu tab id was built from the display text, which varies with language in use. Also no attempt to conform to HTML spec leaving spaces and other non-permitted characters.
Id values now start with 'modmenu_' and then an integer based on position 0-n. The active menu tab still has id attribute of 'current'
=> Fix non-conforming id elements in module menu tabs

htdocs/kernel/block.php
=> Fix return value in deprecated XoopsBlock::store()

htdocs/xoops_lib/modules/protector/admin/center.php
Replaces sort function with one capable of handling both IPv4 and IPv6 addresses and is PHP 8.1 clean.
The inclusion of IPv6 addresses required a small change in how short duration ban times are shown in the Bad IPs list. The
separator between the address and time was a ':' and is now a '|'. IPv6 addresses use the colon, so this needed to be changed.
Also some small UI tweaks to make display of IPv6 addresses more readable.
Add Chrome to the short useragent logic.
Fixes #1151
=> Fix issues with Bad IP list in Protector Center

htdocs/kernel/notification.php
=> XoopsNotification::getByItemId() uses wrong column info

htdocs/class/xoopssecurity.php, htdocs/install/include/makedata.php
- Remove unset()s, fixes #1085
- Use Xmf\IPAddress::fromRequest() to obtain address (does proxy check)
- Correct sample added by installer with "\." needed for regex
=> Cleanup in \XoopsSecurity::checkBadips()

htdocs/class/smarty/xoops_plugins/function.xoStats.php
This was submitted by liomj in #898
The code was modified to add caching to reduce the load on a busy system.
Example use:
```
<{xoStats}>
Latest Member : <a href="<{$xoops_url}>/userinfo.php?uid=<{$latestUid}>"><{$latestMemberUname}></a><br>
Total Posts   : <{$totalPosts}><br>
Total Users   : <{$totalUsers}><br>
Total Online  : <{$totalOnline}><br>
New Users Today     : <{$newUsersToday}><br>
New Users Yesterday : <{$newUsersYesterday}><br>
```
These are the names of all the values that will be assigned for Smarty
- $latestMemberName - name of newest member
- $latestMemberUname - uname of newest member
- $latestUid - uid of newest member
- $totalOnline - total members online
- $totalPosts - total posts by all members
- $newUsersToday - number of members registered today
- …
=> Mini stats Smarty plugin xoStats

htdocs/kernel/object.php
signatures have to be the same or PHP8 complains.
All the modules that I checked are using "id"
=> all modules are using 'id", and this is causing issues in PHP8

htdocs/class/module.textsanitizer.php, htdocs/class/smarty/Smarty_Compiler.class.php, htdocs/class/smarty/xoops_plugins/function.year.php, htdocs/class/theme.php, htdocs/modules/system/themes/dark/xotpl/xo_footer.tpl, htdocs/modules/system/themes/default/xotpl/xo_footer.tpl, htdocs/modules/system/themes/transition/xotpl/xo_footer.tpl
Smarty even at the latest version has dependence on some function deprecated in PHP8.1 (i.e. strftime)
We need some work arounds to get by:
- Implement a `<{year}>` function to replace the current `<{$smarty.now|date_format:"%Y"}>` used in admin footers.
- Patch Smarty_Compiler.class.php to fix timestamp added to compile files along with other very visible errors under PHP 8.1 (sorry, there are many whitespace only changes, specifically tabs to spaces.) 
- PHP 8.1 issue in \xos_opal_Theme class
- PHP 8.1 issue in MyTextSanitizer
=> Clear some Smarty and other php8.1 issues

htdocs/kernel/avatar.php, htdocs/misc.php
If a System avatar was marked false for display, it still was displayed in the misc.php window. This caused issues matching selections to edituser display -- off by one for each false avatar_display.
=> Avatar display in misc.php should respect avatar_display

htdocs/class/xoopsform/formelement.php
Passing null to parameter #1 ($string) of type string is deprecated in file /class/xoopsform/formelement.php line 160
=> Passing null to parameter #1 ($string) of type string is deprecated

htdocs/class/file/folder.php
Unknown: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in file /class/file/folder.php line 291
Unknown: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in file /class/file/folder.php line 852
=> Unknown: preg_match(): Passing null to parameter #2

htdocs/modules/system/class/menu.php
Regression introduced in #1179 showed new element id instead of tab name text
=> Fix module admin breadcrumb

htdocs/install/page_dbsettings.php
in mySQL 8.0.30 utf8 as an alias for utf8mb3 character set has been removed, causing an error: 
Undefined index: utf8 in \install\include\functions.php on line 320
The recommended character set is utf8mb4
see: https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8.html
=> change utf8 to utf8mb4 in install

htdocs/admin.php
Now XOOPS detects all "install" folders and displays a warning in the administration page.
For example, the folder "install_remove_096134593763c074f133e13" was not detected before and there was no warning message to say to remove this folder. Now all "install*" folders are detected. This is better for security.
=> Added security with the "install" folder.

upgrade/upd_2.5.10-to-2.5.11/index.php
During this commit:
https://github.com/XOOPS/XoopsCore25/commit/bffcbdd0380063a1bf9853be4561268a962b26ff
line 531 has been modified. The problem is that the patch is no longer applied to the "version" column of the "modules" table. This creates problems for updating modules. I propose to return as before. We can also put a clearer condition because I don't find the code very easy to read.
What do you think?
=> fix install table modules (version)

htdocs/banners.php, htdocs/language/english/user.php, htdocs/modules/profile/language/english/admin.php, htdocs/modules/profile/userinfo.php, htdocs/modules/system/language/english/admin/preferences.php, htdocs/modules/system/language/english/help/avatars.html, htdocs/xoops_lib/modules/protector/include/postcheck_functions.php, htdocs/xoops_lib/modules/protector/language/english/modinfo.php, htdocs/xoops_lib/modules/protector/library/HTMLPurifier/Strategy/MakeWellFormed.php
and fixed some typos/adjusted some wording in related lines.
Replacing "allowed to allowed to" with "allowed to access" is very much a guess as to the original intended meaning (based on the surrounding lines), I may well have misinterpreted these lines.
Also, I skipped an instance of "his" in the following (on line 41):
https://github.com/XOOPS/XoopsCore25/blob/dfc2ef634c69db8ff337098021faa2c822aed547/htdocs/xoops_lib/modules/protector/library/HTMLPurifier/URIScheme.php#L39-L41
My guess is that that was supposed to be "this" or "is" (or possibly could be omitted entirely?) but the phrasing of the proceeding line is not clear enough (for me) to determine precisely what should be written here.
=> Changed to use gender-neutral pronouns

htdocs/kernel/notification.php
i.e., prevent deactivated users from being sent notifications.
Returning `true` for consistency with the other return values.
=> Set to only send notifications to activated users

htdocs/modules/system/templates/blocks/system_block_siteinfo.tpl, htdocs/themes/xbootstrap/modules/system/blocks/system_block_siteinfo.tpl, htdocs/themes/xswatch4/modules/system/blocks/system_block_siteinfo.tpl
The test  of $block.showgroups should be **before** the table tag. Why ?
Cause if $block.showgroups == false, the result is a useless empty table in the code.
I have a question on another point :
Why test 
```
<{foreach item=group from=$block.groups}>
```
?
Cause there is only the webmasters group displayed, no other group in this bloc.
So, I think this test is useless, I think we should pick up the group webmasters, no need to use a foreach for that.
No ?
=>  update siteinfo bloc and 1 question

htdocs/class/smarty/xoops_plugins/modifier.truncateHtml.php
"preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated" error in php 8.1
=> fix error with preg_split() and php 8.1

htdocs/modules/system/help.php
During this PR (https://github.com/XOOPS/XoopsCore25/pull/1126), I did not change the help.php file. I don't understand why there is the version number in this file but it must be corrected. It's ok now.
It is the wgtestui control module that found this problem. Congratulations for this module!
=> Fix: Error in help.php

htdocs/include/functions.php
creates errors when used in date(), e.g.
`TypeError: date(): Argument #2 ($timestamp) must be of type ?int, float given in file /modules/xoopspoll/class/Renderer.php line 168`
=> xoops_getUserTimestamp has to return integer

htdocs/include/functions.php
- add makeSet() function to simplify setting default for a missing variable
- also has tab to space conversion for file
The makeSet() function is intended to reduce the complexity often proliferated using the PHP isset() function. 
In short, this function can replace:
```PHP
if (!isset($options) {
$options = '';
}
doStuff($options);
```
with:
```PHP
doStuff(makeSet($options,''));
```
=> Add makeSet()

htdocs/install/include/common.inc.php, htdocs/install/include/install_tpl.php, htdocs/install/include/makedata.php, htdocs/install/page_configsite.php, htdocs/install/page_siteinit.php, htdocs/install/page_tablescreate.php, htdocs/install/page_tablesfill.php, htdocs/install/page_theme.php, upgrade/class/control.php
Correct errors in the path declarations in install and update
Some of the  changes in #1344 had issues where relative paths that were specified originally (which were based on current working directory in the PHP process) were replaced with incorrect PHP `__DIR__` paths, which are relative to the current PHP file. It can be confusing ;)
=> Dir install upgrade

htdocs/install/page_tablesfill.php
=> Incorrect language checking in install tablesfill step

htdocs/install/page_configsave.php
This was causing problems when I was logging with "`https://`" because every link with XOOPS_URL would point automatically to "`http://`"
=> XOOPS_URL was hardcoded with "http://"

htdocs/xoops_lib/modules/protector/admin/about.php, htdocs/xoops_lib/modules/protector/admin/admin_header.php, htdocs/xoops_lib/modules/protector/admin/advisory.php, htdocs/xoops_lib/modules/protector/admin/prefix_manager.php
There was a conflict when the ` /xoops_lib` folder was outside of the document root
=> Fixing paths in Protector

htdocs/class/auth/auth_ldap.php, htdocs/class/auth/auth_provisionning.php, htdocs/class/xoopslocal.php, htdocs/include/functions.php, htdocs/modules/system/admin/tplsets/main.php
something to consider?
In modules, I'll be changing all utf8_encode() and uf8_decode() to mb_convert_encoding()
=> consistency in dealing with deprecated in PHP 8.2 utf8_encode() and utf8_decode()

htdocs/class/logger/xoopslogger.php
Currently it only shows the exception location, but it we don't know where the issue originated
=> handleException() adds own trace when calling handleError()

htdocs/class/captcha/image/scripts/image.php, htdocs/class/uploader.php
originally XOOPS created this name:
images/img64eb5c3654644.jpg
By adding "true" to uniqid(), XOOPS creates longer name, which doesn't fit into the DB, as the field size is only 30:
'images/img65596d11ac6014.17681140.jpg
=> Reverse adding more entropy (image_name field size in DB is too small

htdocs/modules/system/xoops_version.php
I've experienced it today on two websites that I was upgrading: after the upgrade finished, and was going to update the System module, I've got fatal error that XOOPS couldn't find ```_MI_SYSTEM_NAME``` in xoops_version.php :
``` $modversion['name']        = _MI_SYSTEM_NAME;```
I don't know why, and right now don't have time to investigate. After I added the line, it worked.
=> load modinfo language in /system/xoops_version.php, after upgrade

htdocs/Frameworks/moduleclasses/moduleadmin/moduleadmin.php, htdocs/include/version.php, htdocs/modules/pm/xoops_version.php, htdocs/modules/profile/xoops_version.php, htdocs/xoops_lib/modules/protector/xoops_version.php
@GregMage When I compared 'min_xoops" from a module as "2.5.11" to the XOOPS version as "2.5.11-Stable", the PHP version_compare() didn't work, telling me that I don't have the required minimum PHP version. 
Once I've changed it to  ```$this->_obj->versionCompare()```, it worked.
Can you check if this is correct?
=> Updating versions, fix for versionCompare()

htdocs/include/common.php
Unix will check for "/modules/"
Windows will check for "/MoDuLeS/"
Related to #1419
=> Case insensitive path check

htdocs/class/module.textsanitizer.php
**Color pattern:**
**_Problem:_** The pattern ```/\[color=(['\"]?)([a-zA-Z0-9#]*)\\1](.*)\[\/color\]/sU``` is expecting the color value to be enclosed in either single quotes or double quotes, but the example ```[color=009900]``` doesn't have any quotes.
**_Solution:_** We remove the quote capturing group and make it optional:  ```/\[color=(['\"]?)([a-zA-Z0-9#]+)\\1?](.*)\[\/color\]/sU```
**Size pattern:**
**_Problem:_** The pattern ```/\[size=(['\"]?)([a-zA-Z0-9.#]*)\\1](.*)\[\/size\]/sU``` is allowing dot (```.```) and hash (```#```) characters in the size value, which are not valid for font sizes.
**_Solution:_** We remove the dot  (```.```) and hash (```#```) characters from the size value capturing group: ```/\[size=(['\"]?)([a-zA-Z0-9-]+)\\1?](.*)\[\/size\]/sU```
The updated …
=> Fix for https://github.com/XOOPS/XoopsCore25/issues/1458

htdocs/themes/xswatch4/modules/system/system_search.tpl
search result was not shown after clicking "Show all results" as ` if isset($nomatch) && $nomatch == true` is only fulfilled if there is no match
=> fixed bug in search tpl

htdocs/install/include/common.inc.php
During installation, I got this error htdocs/install/include/../../class/libraries/vendor/autoload.php): Failed to open stream: No such file or directory in htdocs/install/include/common.inc.php on line 89
The installation stopped at /install/page_pathsettings.php
I set the new path for vendor/autoload.php in common.inc.php and I was able to install Xoops without errors
=> New path for composer files in install file

htdocs/themes/xbootstrap5/modules/news/news_article.tpl
In article.php, tags smarty var is always set (with true or false)
But news_article.tpl only check if var isset, so it always try to load the db:tag_bar.tpl
=> Fix tag.tpl always loading in modules/news

htdocs/class/xoopssecurity.php, htdocs/kernel/session.php, htdocs/modules/system/themes/ComposerInfo.php
Context :  My admin preferences (modules & main) was not always saved.
**htdocs/modules/system/themes/ComposerInfo.php**
I checked and found an error 404 in the browser network tab. It was from the file : htdocs/modules/system/themes/ComposerInfo.php  . I comment the line but it didn't resolve the problem. But I think it's better commented.
**htdocs/class/xoopssecurity.php**
I found that an invalid token was aborting the save with a redirection.
The token was not saved in the session (xoops_session table) but was set correctly in $_SESSION 
So I forced the updating of the session in database with add **`session_write_close();`**
**htdocs/kernel/session.php**
I had an SQL duplicate index error with an INSERT comment in xoops_session
The fault was this test ` if …
=> Fix problem with admin save preference

htdocs/mainfile.dist.php
$_SERVER['HTTPS'] is set only when HTTPS protocol (as described on php.net) 
So `$http` was never set to `$http='http://'`
Cookie session was created with secure=true even with `http` connection and it was not working with Safari browser.
=> http is default

htdocs/class/xoopssecurity.php
[PR#1511](https://github.com/XOOPS/XoopsCore25/pull/1511) introduced a new bug: 
when calling: `$GLOBALS['xoopsSecurity']->check()`, it was returning error:  'No valid token found' because by calling session_write_close() in createToken(), the session is closed prematurely. When the script continues execution (e.g., during token validation), the session is no longer active, and attempts to access or modify $_SESSION fail or start a new session, resulting in the token not being found.
Commenting out session_write_close() keeps the session open, so $_SESSION remains accessible, and validateToken() should find the token without needing to restart the session. 
As a safeguard, I've added in `validateToken()`:
```php
if (session_status() !== PHP_SESSION_ACTIVE) {
session_start();
}
```
=> fix for new bug from PR#1511

htdocs/kernel/module.php, htdocs/modules/pm/xoops_version.php, htdocs/modules/profile/xoops_version.php, htdocs/modules/system/blocks/system_blocks.php, htdocs/themes/xbootstrap5/css/reset.css, htdocs/themes/xbootstrap5/modules/system/blocks/system_block_mainmenu.tpl, htdocs/themes/xbootstrap5/style.css
By adding Font Awesome icons to module and submenu items in xoops_version.php:
you can have now in xbootstrap5 theme individual icons for the menu items:
What do you think?
=> New feature: menu icons for modules

htdocs/class/xoopsstory.php, htdocs/class/xoopstopic.php, htdocs/edituser.php, htdocs/lostpass.php, htdocs/modules/profile/activate.php, htdocs/modules/profile/edituser.php, htdocs/modules/profile/lostpass.php, htdocs/modules/profile/search.php, htdocs/modules/system/admin/users/main.php, htdocs/search.php
Related to this point:
https://github.com/XOOPS/XoopsCore25/issues/1564
Xoops should not use the deprecated ‘addSlashes’ function in its core.
This PR fixes this error.
=> Fix Deprecated addSlashes
